/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ./ExprCppTree.g
 *     -                            On : 2019-04-18 18:00:17
 *     -                 for the lexer : ExprCppTreeLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ExprCppTreeLexer.h"
/* ----------------------------------------- */


/** String literals used by ExprCppTreeLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x7B, 0x7D,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pExprCppTreeLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pExprCppTreeLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pExprCppTreeLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pExprCppTreeLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mT__32    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mT__33    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mT__34    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mT__35    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mT__36    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mPLUS    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mMINUS    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mTIMES    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mDIV    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mDOT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mASSIGN    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mDEF    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mIF    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mELSE    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mGT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mGEQ    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mLS    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mLEQ    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mEQ    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mNOT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOR    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mAND    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mBITOR    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mBITAND    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mPRINT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mFOR    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mWHILE    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mBREAK    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mCONTINUE    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mID    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mINT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mBLOCK    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mWS    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pExprCppTreeLexer ctx);
static void	ExprCppTreeLexerFree(pExprCppTreeLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
ExprCppTreeLexerFree  (pExprCppTreeLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
ExprCppTreeLexerReset (pExprCppTreeLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "./ExprCppTree.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called ExprCppTreeLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pExprCppTreeLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pExprCppTreeLexer ExprCppTreeLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return ExprCppTreeLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called ExprCppTreeLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pExprCppTreeLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pExprCppTreeLexer ExprCppTreeLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pExprCppTreeLexer ctx; // Context structure we will build and return

    ctx = (pExprCppTreeLexer) ANTLR3_CALLOC(1, sizeof(ExprCppTreeLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in ExprCppTreeLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our ExprCppTreeLexer interface
     */
    ctx->mT__32	= mT__32;
    ctx->mT__33	= mT__33;
    ctx->mT__34	= mT__34;
    ctx->mT__35	= mT__35;
    ctx->mT__36	= mT__36;
    ctx->mPLUS	= mPLUS;
    ctx->mMINUS	= mMINUS;
    ctx->mTIMES	= mTIMES;
    ctx->mDIV	= mDIV;
    ctx->mDOT	= mDOT;
    ctx->mASSIGN	= mASSIGN;
    ctx->mDEF	= mDEF;
    ctx->mIF	= mIF;
    ctx->mELSE	= mELSE;
    ctx->mGT	= mGT;
    ctx->mGEQ	= mGEQ;
    ctx->mLS	= mLS;
    ctx->mLEQ	= mLEQ;
    ctx->mEQ	= mEQ;
    ctx->mNOT	= mNOT;
    ctx->mOR	= mOR;
    ctx->mAND	= mAND;
    ctx->mBITOR	= mBITOR;
    ctx->mBITAND	= mBITAND;
    ctx->mPRINT	= mPRINT;
    ctx->mFOR	= mFOR;
    ctx->mWHILE	= mWHILE;
    ctx->mBREAK	= mBREAK;
    ctx->mCONTINUE	= mCONTINUE;
    ctx->mID	= mID;
    ctx->mINT	= mINT;
    ctx->mBLOCK	= mBLOCK;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= ExprCppTreeLexerFree;
    ctx->reset          = ExprCppTreeLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:7: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__32
 *
 * Looks to match the characters the constitute the token T__32
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__32(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__32;


    // ./ExprCppTree.g:7:7: ( '(' )
    // ./ExprCppTree.g:7:9: '('
    {
        MATCHC('(');
        if  (HASEXCEPTION())
        {
            goto ruleT__32Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__32Ex; /* Prevent compiler warnings */
    ruleT__32Ex: ;

}
// $ANTLR end T__32

//   Comes from: 8:7: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__33
 *
 * Looks to match the characters the constitute the token T__33
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__33(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__33;


    // ./ExprCppTree.g:8:7: ( ')' )
    // ./ExprCppTree.g:8:9: ')'
    {
        MATCHC(')');
        if  (HASEXCEPTION())
        {
            goto ruleT__33Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__33Ex; /* Prevent compiler warnings */
    ruleT__33Ex: ;

}
// $ANTLR end T__33

//   Comes from: 9:7: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__34
 *
 * Looks to match the characters the constitute the token T__34
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__34(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__34;


    // ./ExprCppTree.g:9:7: ( ';' )
    // ./ExprCppTree.g:9:9: ';'
    {
        MATCHC(';');
        if  (HASEXCEPTION())
        {
            goto ruleT__34Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__34Ex; /* Prevent compiler warnings */
    ruleT__34Ex: ;

}
// $ANTLR end T__34

//   Comes from: 10:7: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__35
 *
 * Looks to match the characters the constitute the token T__35
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__35(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__35;


    // ./ExprCppTree.g:10:7: ( '{' )
    // ./ExprCppTree.g:10:9: '{'
    {
        MATCHC('{');
        if  (HASEXCEPTION())
        {
            goto ruleT__35Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__35Ex; /* Prevent compiler warnings */
    ruleT__35Ex: ;

}
// $ANTLR end T__35

//   Comes from: 11:7: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__36
 *
 * Looks to match the characters the constitute the token T__36
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__36(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__36;


    // ./ExprCppTree.g:11:7: ( '}' )
    // ./ExprCppTree.g:11:9: '}'
    {
        MATCHC('}');
        if  (HASEXCEPTION())
        {
            goto ruleT__36Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__36Ex; /* Prevent compiler warnings */
    ruleT__36Ex: ;

}
// $ANTLR end T__36

//   Comes from: 14:5: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PLUS
 *
 * Looks to match the characters the constitute the token PLUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPLUS(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PLUS;


    // ./ExprCppTree.g:14:5: ( '+' )
    // ./ExprCppTree.g:14:7: '+'
    {
        MATCHC('+');
        if  (HASEXCEPTION())
        {
            goto rulePLUSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto rulePLUSEx; /* Prevent compiler warnings */
    rulePLUSEx: ;

}
// $ANTLR end PLUS

//   Comes from: 15:6: ( '-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MINUS
 *
 * Looks to match the characters the constitute the token MINUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMINUS(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = MINUS;


    // ./ExprCppTree.g:15:6: ( '-' )
    // ./ExprCppTree.g:15:8: '-'
    {
        MATCHC('-');
        if  (HASEXCEPTION())
        {
            goto ruleMINUSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleMINUSEx; /* Prevent compiler warnings */
    ruleMINUSEx: ;

}
// $ANTLR end MINUS

//   Comes from: 16:6: ( '*' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start TIMES
 *
 * Looks to match the characters the constitute the token TIMES
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mTIMES(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = TIMES;


    // ./ExprCppTree.g:16:6: ( '*' )
    // ./ExprCppTree.g:16:8: '*'
    {
        MATCHC('*');
        if  (HASEXCEPTION())
        {
            goto ruleTIMESEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleTIMESEx; /* Prevent compiler warnings */
    ruleTIMESEx: ;

}
// $ANTLR end TIMES

//   Comes from: 17:4: ( '/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DIV
 *
 * Looks to match the characters the constitute the token DIV
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDIV(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DIV;


    // ./ExprCppTree.g:17:4: ( '/' )
    // ./ExprCppTree.g:17:6: '/'
    {
        MATCHC('/');
        if  (HASEXCEPTION())
        {
            goto ruleDIVEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleDIVEx; /* Prevent compiler warnings */
    ruleDIVEx: ;

}
// $ANTLR end DIV

//   Comes from: 18:4: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DOT
 *
 * Looks to match the characters the constitute the token DOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDOT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DOT;


    // ./ExprCppTree.g:18:4: ( ',' )
    // ./ExprCppTree.g:18:6: ','
    {
        MATCHC(',');
        if  (HASEXCEPTION())
        {
            goto ruleDOTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleDOTEx; /* Prevent compiler warnings */
    ruleDOTEx: ;

}
// $ANTLR end DOT

//   Comes from: 19:7: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ASSIGN
 *
 * Looks to match the characters the constitute the token ASSIGN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mASSIGN(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ASSIGN;


    // ./ExprCppTree.g:19:7: ( '=' )
    // ./ExprCppTree.g:19:9: '='
    {
        MATCHC('=');
        if  (HASEXCEPTION())
        {
            goto ruleASSIGNEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleASSIGNEx; /* Prevent compiler warnings */
    ruleASSIGNEx: ;

}
// $ANTLR end ASSIGN

//   Comes from: 21:4: ( 'd' 'e' 'f' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DEF
 *
 * Looks to match the characters the constitute the token DEF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDEF(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DEF;


    // ./ExprCppTree.g:21:4: ( 'd' 'e' 'f' )
    // ./ExprCppTree.g:21:6: 'd' 'e' 'f'
    {
        MATCHC('d');
        if  (HASEXCEPTION())
        {
            goto ruleDEFEx;
        }


        MATCHC('e');
        if  (HASEXCEPTION())
        {
            goto ruleDEFEx;
        }


        MATCHC('f');
        if  (HASEXCEPTION())
        {
            goto ruleDEFEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleDEFEx; /* Prevent compiler warnings */
    ruleDEFEx: ;

}
// $ANTLR end DEF

//   Comes from: 22:3: ( 'i' 'f' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start IF
 *
 * Looks to match the characters the constitute the token IF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mIF(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = IF;


    // ./ExprCppTree.g:22:3: ( 'i' 'f' )
    // ./ExprCppTree.g:22:5: 'i' 'f'
    {
        MATCHC('i');
        if  (HASEXCEPTION())
        {
            goto ruleIFEx;
        }


        MATCHC('f');
        if  (HASEXCEPTION())
        {
            goto ruleIFEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleIFEx; /* Prevent compiler warnings */
    ruleIFEx: ;

}
// $ANTLR end IF

//   Comes from: 23:5: ( 'e' 'l' 's' 'e' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ELSE
 *
 * Looks to match the characters the constitute the token ELSE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mELSE(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ELSE;


    // ./ExprCppTree.g:23:5: ( 'e' 'l' 's' 'e' )
    // ./ExprCppTree.g:23:7: 'e' 'l' 's' 'e'
    {
        MATCHC('e');
        if  (HASEXCEPTION())
        {
            goto ruleELSEEx;
        }


        MATCHC('l');
        if  (HASEXCEPTION())
        {
            goto ruleELSEEx;
        }


        MATCHC('s');
        if  (HASEXCEPTION())
        {
            goto ruleELSEEx;
        }


        MATCHC('e');
        if  (HASEXCEPTION())
        {
            goto ruleELSEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleELSEEx; /* Prevent compiler warnings */
    ruleELSEEx: ;

}
// $ANTLR end ELSE

//   Comes from: 25:3: ( '>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start GT
 *
 * Looks to match the characters the constitute the token GT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mGT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = GT;


    // ./ExprCppTree.g:25:3: ( '>' )
    // ./ExprCppTree.g:25:5: '>'
    {
        MATCHC('>');
        if  (HASEXCEPTION())
        {
            goto ruleGTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleGTEx; /* Prevent compiler warnings */
    ruleGTEx: ;

}
// $ANTLR end GT

//   Comes from: 26:4: ( '>' '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start GEQ
 *
 * Looks to match the characters the constitute the token GEQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mGEQ(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = GEQ;


    // ./ExprCppTree.g:26:4: ( '>' '=' )
    // ./ExprCppTree.g:26:6: '>' '='
    {
        MATCHC('>');
        if  (HASEXCEPTION())
        {
            goto ruleGEQEx;
        }


        MATCHC('=');
        if  (HASEXCEPTION())
        {
            goto ruleGEQEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleGEQEx; /* Prevent compiler warnings */
    ruleGEQEx: ;

}
// $ANTLR end GEQ

//   Comes from: 27:3: ( '<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LS
 *
 * Looks to match the characters the constitute the token LS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLS(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LS;


    // ./ExprCppTree.g:27:3: ( '<' )
    // ./ExprCppTree.g:27:5: '<'
    {
        MATCHC('<');
        if  (HASEXCEPTION())
        {
            goto ruleLSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLSEx; /* Prevent compiler warnings */
    ruleLSEx: ;

}
// $ANTLR end LS

//   Comes from: 28:4: ( '<' '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LEQ
 *
 * Looks to match the characters the constitute the token LEQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLEQ(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LEQ;


    // ./ExprCppTree.g:28:4: ( '<' '=' )
    // ./ExprCppTree.g:28:6: '<' '='
    {
        MATCHC('<');
        if  (HASEXCEPTION())
        {
            goto ruleLEQEx;
        }


        MATCHC('=');
        if  (HASEXCEPTION())
        {
            goto ruleLEQEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLEQEx; /* Prevent compiler warnings */
    ruleLEQEx: ;

}
// $ANTLR end LEQ

//   Comes from: 29:3: ( '=' '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EQ
 *
 * Looks to match the characters the constitute the token EQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEQ(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = EQ;


    // ./ExprCppTree.g:29:3: ( '=' '=' )
    // ./ExprCppTree.g:29:5: '=' '='
    {
        MATCHC('=');
        if  (HASEXCEPTION())
        {
            goto ruleEQEx;
        }


        MATCHC('=');
        if  (HASEXCEPTION())
        {
            goto ruleEQEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleEQEx; /* Prevent compiler warnings */
    ruleEQEx: ;

}
// $ANTLR end EQ

//   Comes from: 30:4: ( '!' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NOT
 *
 * Looks to match the characters the constitute the token NOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNOT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NOT;


    // ./ExprCppTree.g:30:4: ( '!' )
    // ./ExprCppTree.g:30:6: '!'
    {
        MATCHC('!');
        if  (HASEXCEPTION())
        {
            goto ruleNOTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNOTEx; /* Prevent compiler warnings */
    ruleNOTEx: ;

}
// $ANTLR end NOT

//   Comes from: 31:3: ( '|' '|' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OR
 *
 * Looks to match the characters the constitute the token OR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOR(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OR;


    // ./ExprCppTree.g:31:3: ( '|' '|' )
    // ./ExprCppTree.g:31:5: '|' '|'
    {
        MATCHC('|');
        if  (HASEXCEPTION())
        {
            goto ruleOREx;
        }


        MATCHC('|');
        if  (HASEXCEPTION())
        {
            goto ruleOREx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOREx; /* Prevent compiler warnings */
    ruleOREx: ;

}
// $ANTLR end OR

//   Comes from: 32:4: ( '&' '&' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start AND
 *
 * Looks to match the characters the constitute the token AND
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mAND(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = AND;


    // ./ExprCppTree.g:32:4: ( '&' '&' )
    // ./ExprCppTree.g:32:6: '&' '&'
    {
        MATCHC('&');
        if  (HASEXCEPTION())
        {
            goto ruleANDEx;
        }


        MATCHC('&');
        if  (HASEXCEPTION())
        {
            goto ruleANDEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleANDEx; /* Prevent compiler warnings */
    ruleANDEx: ;

}
// $ANTLR end AND

//   Comes from: 33:6: ( '|' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BITOR
 *
 * Looks to match the characters the constitute the token BITOR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBITOR(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = BITOR;


    // ./ExprCppTree.g:33:6: ( '|' )
    // ./ExprCppTree.g:33:8: '|'
    {
        MATCHC('|');
        if  (HASEXCEPTION())
        {
            goto ruleBITOREx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleBITOREx; /* Prevent compiler warnings */
    ruleBITOREx: ;

}
// $ANTLR end BITOR

//   Comes from: 34:7: ( '&' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BITAND
 *
 * Looks to match the characters the constitute the token BITAND
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBITAND(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = BITAND;


    // ./ExprCppTree.g:34:7: ( '&' )
    // ./ExprCppTree.g:34:9: '&'
    {
        MATCHC('&');
        if  (HASEXCEPTION())
        {
            goto ruleBITANDEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleBITANDEx; /* Prevent compiler warnings */
    ruleBITANDEx: ;

}
// $ANTLR end BITAND

//   Comes from: 36:6: ( 'p' 'r' 'i' 'n' 't' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PRINT
 *
 * Looks to match the characters the constitute the token PRINT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPRINT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PRINT;


    // ./ExprCppTree.g:36:6: ( 'p' 'r' 'i' 'n' 't' )
    // ./ExprCppTree.g:36:8: 'p' 'r' 'i' 'n' 't'
    {
        MATCHC('p');
        if  (HASEXCEPTION())
        {
            goto rulePRINTEx;
        }


        MATCHC('r');
        if  (HASEXCEPTION())
        {
            goto rulePRINTEx;
        }


        MATCHC('i');
        if  (HASEXCEPTION())
        {
            goto rulePRINTEx;
        }


        MATCHC('n');
        if  (HASEXCEPTION())
        {
            goto rulePRINTEx;
        }


        MATCHC('t');
        if  (HASEXCEPTION())
        {
            goto rulePRINTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto rulePRINTEx; /* Prevent compiler warnings */
    rulePRINTEx: ;

}
// $ANTLR end PRINT

//   Comes from: 37:4: ( 'f' 'o' 'r' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start FOR
 *
 * Looks to match the characters the constitute the token FOR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mFOR(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = FOR;


    // ./ExprCppTree.g:37:4: ( 'f' 'o' 'r' )
    // ./ExprCppTree.g:37:6: 'f' 'o' 'r'
    {
        MATCHC('f');
        if  (HASEXCEPTION())
        {
            goto ruleFOREx;
        }


        MATCHC('o');
        if  (HASEXCEPTION())
        {
            goto ruleFOREx;
        }


        MATCHC('r');
        if  (HASEXCEPTION())
        {
            goto ruleFOREx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleFOREx; /* Prevent compiler warnings */
    ruleFOREx: ;

}
// $ANTLR end FOR

//   Comes from: 38:6: ( 'w' 'h' 'i' 'l' 'e' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WHILE
 *
 * Looks to match the characters the constitute the token WHILE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWHILE(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WHILE;


    // ./ExprCppTree.g:38:6: ( 'w' 'h' 'i' 'l' 'e' )
    // ./ExprCppTree.g:38:8: 'w' 'h' 'i' 'l' 'e'
    {
        MATCHC('w');
        if  (HASEXCEPTION())
        {
            goto ruleWHILEEx;
        }


        MATCHC('h');
        if  (HASEXCEPTION())
        {
            goto ruleWHILEEx;
        }


        MATCHC('i');
        if  (HASEXCEPTION())
        {
            goto ruleWHILEEx;
        }


        MATCHC('l');
        if  (HASEXCEPTION())
        {
            goto ruleWHILEEx;
        }


        MATCHC('e');
        if  (HASEXCEPTION())
        {
            goto ruleWHILEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWHILEEx; /* Prevent compiler warnings */
    ruleWHILEEx: ;

}
// $ANTLR end WHILE

//   Comes from: 39:6: ( 'b' 'r' 'e' 'a' 'k' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BREAK
 *
 * Looks to match the characters the constitute the token BREAK
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBREAK(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = BREAK;


    // ./ExprCppTree.g:39:6: ( 'b' 'r' 'e' 'a' 'k' )
    // ./ExprCppTree.g:39:8: 'b' 'r' 'e' 'a' 'k'
    {
        MATCHC('b');
        if  (HASEXCEPTION())
        {
            goto ruleBREAKEx;
        }


        MATCHC('r');
        if  (HASEXCEPTION())
        {
            goto ruleBREAKEx;
        }


        MATCHC('e');
        if  (HASEXCEPTION())
        {
            goto ruleBREAKEx;
        }


        MATCHC('a');
        if  (HASEXCEPTION())
        {
            goto ruleBREAKEx;
        }


        MATCHC('k');
        if  (HASEXCEPTION())
        {
            goto ruleBREAKEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleBREAKEx; /* Prevent compiler warnings */
    ruleBREAKEx: ;

}
// $ANTLR end BREAK

//   Comes from: 40:9: ( 'c' 'o' 'n' 't' 'i' 'n' 'u' 'e' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CONTINUE
 *
 * Looks to match the characters the constitute the token CONTINUE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCONTINUE(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CONTINUE;


    // ./ExprCppTree.g:40:9: ( 'c' 'o' 'n' 't' 'i' 'n' 'u' 'e' )
    // ./ExprCppTree.g:40:11: 'c' 'o' 'n' 't' 'i' 'n' 'u' 'e'
    {
        MATCHC('c');
        if  (HASEXCEPTION())
        {
            goto ruleCONTINUEEx;
        }


        MATCHC('o');
        if  (HASEXCEPTION())
        {
            goto ruleCONTINUEEx;
        }


        MATCHC('n');
        if  (HASEXCEPTION())
        {
            goto ruleCONTINUEEx;
        }


        MATCHC('t');
        if  (HASEXCEPTION())
        {
            goto ruleCONTINUEEx;
        }


        MATCHC('i');
        if  (HASEXCEPTION())
        {
            goto ruleCONTINUEEx;
        }


        MATCHC('n');
        if  (HASEXCEPTION())
        {
            goto ruleCONTINUEEx;
        }


        MATCHC('u');
        if  (HASEXCEPTION())
        {
            goto ruleCONTINUEEx;
        }


        MATCHC('e');
        if  (HASEXCEPTION())
        {
            goto ruleCONTINUEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCONTINUEEx; /* Prevent compiler warnings */
    ruleCONTINUEEx: ;

}
// $ANTLR end CONTINUE

//   Comes from: 74:3: ( ( 'a' .. 'z' | 'A' .. 'Z' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ID
 *
 * Looks to match the characters the constitute the token ID
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mID(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ID;


    // ./ExprCppTree.g:74:3: ( ( 'a' .. 'z' | 'A' .. 'Z' )+ )
    // ./ExprCppTree.g:74:5: ( 'a' .. 'z' | 'A' .. 'Z' )+
    {
        // ./ExprCppTree.g:74:5: ( 'a' .. 'z' | 'A' .. 'Z' )+
        {
            int cnt1=0;

            for (;;)
            {
                int alt1=2;
        	switch ( LA(1) )
        	{
        	case 'A':
        	case 'B':
        	case 'C':
        	case 'D':
        	case 'E':
        	case 'F':
        	case 'G':
        	case 'H':
        	case 'I':
        	case 'J':
        	case 'K':
        	case 'L':
        	case 'M':
        	case 'N':
        	case 'O':
        	case 'P':
        	case 'Q':
        	case 'R':
        	case 'S':
        	case 'T':
        	case 'U':
        	case 'V':
        	case 'W':
        	case 'X':
        	case 'Y':
        	case 'Z':
        	case 'a':
        	case 'b':
        	case 'c':
        	case 'd':
        	case 'e':
        	case 'f':
        	case 'g':
        	case 'h':
        	case 'i':
        	case 'j':
        	case 'k':
        	case 'l':
        	case 'm':
        	case 'n':
        	case 'o':
        	case 'p':
        	case 'q':
        	case 'r':
        	case 's':
        	case 't':
        	case 'u':
        	case 'v':
        	case 'w':
        	case 'x':
        	case 'y':
        	case 'z':
        		{
        			alt1=1;
        		}
        	    break;

        	}

        	switch (alt1)
        	{
        	    case 1:
        	        // ./ExprCppTree.g:
        	        {
        	            if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleIDEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt1 >= 1 )
        		{
        		    goto loop1;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleIDEx;
        	}
        	cnt1++;
            }
            loop1: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleIDEx; /* Prevent compiler warnings */
    ruleIDEx: ;

}
// $ANTLR end ID

//   Comes from: 75:4: ( ( '~' )? ( '0' .. '9' )+ ( '.' ( '0' .. '9' )+ )? )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INT
 *
 * Looks to match the characters the constitute the token INT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INT;


    // ./ExprCppTree.g:75:4: ( ( '~' )? ( '0' .. '9' )+ ( '.' ( '0' .. '9' )+ )? )
    // ./ExprCppTree.g:75:6: ( '~' )? ( '0' .. '9' )+ ( '.' ( '0' .. '9' )+ )?
    {
        // ./ExprCppTree.g:75:6: ( '~' )?
        {
            int alt2=2;
            switch ( LA(1) )
            {
                case '~':
                	{
                		alt2=1;
                	}
                    break;
            }

            switch (alt2)
            {
        	case 1:
        	    // ./ExprCppTree.g:75:6: '~'
        	    {
        	        MATCHC('~');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleINTEx;
        	        }


        	    }
        	    break;

            }
        }

        // ./ExprCppTree.g:75:11: ( '0' .. '9' )+
        {
            int cnt3=0;

            for (;;)
            {
                int alt3=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt3=1;
        		}
        	    break;

        	}

        	switch (alt3)
        	{
        	    case 1:
        	        // ./ExprCppTree.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleINTEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt3 >= 1 )
        		{
        		    goto loop3;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleINTEx;
        	}
        	cnt3++;
            }
            loop3: ;	/* Jump to here if this rule does not match */
        }

        // ./ExprCppTree.g:75:21: ( '.' ( '0' .. '9' )+ )?
        {
            int alt5=2;
            switch ( LA(1) )
            {
                case '.':
                	{
                		alt5=1;
                	}
                    break;
            }

            switch (alt5)
            {
        	case 1:
        	    // ./ExprCppTree.g:75:22: '.' ( '0' .. '9' )+
        	    {
        	        MATCHC('.');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleINTEx;
        	        }


        	        // ./ExprCppTree.g:75:26: ( '0' .. '9' )+
        	        {
        	            int cnt4=0;

        	            for (;;)
        	            {
        	                int alt4=2;
        	        	switch ( LA(1) )
        	        	{
        	        	case '0':
        	        	case '1':
        	        	case '2':
        	        	case '3':
        	        	case '4':
        	        	case '5':
        	        	case '6':
        	        	case '7':
        	        	case '8':
        	        	case '9':
        	        		{
        	        			alt4=1;
        	        		}
        	        	    break;

        	        	}

        	        	switch (alt4)
        	        	{
        	        	    case 1:
        	        	        // ./ExprCppTree.g:
        	        	        {
        	        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	        	            {
        	        	                CONSUME();
        	        	            }
        	        	            else
        	        	            {
        	        	                CONSTRUCTEX();
        	        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	        	                LRECOVER();
        	        	                goto ruleINTEx;
        	        	            }


        	        	        }
        	        	        break;

        	        	    default:

        	        		if ( cnt4 >= 1 )
        	        		{
        	        		    goto loop4;
        	        		}
        	        		/* mismatchedSetEx()
        	        		 */
        	        		CONSTRUCTEX();
        	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        	        		goto ruleINTEx;
        	        	}
        	        	cnt4++;
        	            }
        	            loop4: ;	/* Jump to here if this rule does not match */
        	        }

        	    }
        	    break;

            }
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleINTEx; /* Prevent compiler warnings */
    ruleINTEx: ;

}
// $ANTLR end INT

//   Comes from: 76:6: ( '{}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BLOCK
 *
 * Looks to match the characters the constitute the token BLOCK
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBLOCK(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = BLOCK;


    // ./ExprCppTree.g:76:6: ( '{}' )
    // ./ExprCppTree.g:76:7: '{}'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleBLOCKEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleBLOCKEx; /* Prevent compiler warnings */
    ruleBLOCKEx: ;

}
// $ANTLR end BLOCK

//   Comes from: 77:4: ( ( ' ' | '\\t' | '\\n' | '\\r' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;


    // ./ExprCppTree.g:77:4: ( ( ' ' | '\\t' | '\\n' | '\\r' )+ )
    // ./ExprCppTree.g:77:6: ( ' ' | '\\t' | '\\n' | '\\r' )+
    {
        // ./ExprCppTree.g:77:6: ( ' ' | '\\t' | '\\n' | '\\r' )+
        {
            int cnt6=0;

            for (;;)
            {
                int alt6=2;
        	switch ( LA(1) )
        	{
        	case '\t':
        	case '\n':
        	case '\r':
        	case ' ':
        		{
        			alt6=1;
        		}
        	    break;

        	}

        	switch (alt6)
        	{
        	    case 1:
        	        // ./ExprCppTree.g:
        	        {
        	            if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleWSEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt6 >= 1 )
        		{
        		    goto loop6;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWSEx;
        	}
        	cnt6++;
            }
            loop6: ;	/* Jump to here if this rule does not match */
        }

        {
            LEXSTATE->channel = HIDDEN;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pExprCppTreeLexer ctx)
{
    {
        //  ./ExprCppTree.g:1:8: ( T__32 | T__33 | T__34 | T__35 | T__36 | PLUS | MINUS | TIMES | DIV | DOT | ASSIGN | DEF | IF | ELSE | GT | GEQ | LS | LEQ | EQ | NOT | OR | AND | BITOR | BITAND | PRINT | FOR | WHILE | BREAK | CONTINUE | ID | INT | BLOCK | WS )

        ANTLR3_UINT32 alt7;

        alt7=33;

        switch ( LA(1) )
        {
        case '(':
        	{
        		alt7=1;
        	}
            break;
        case ')':
        	{
        		alt7=2;
        	}
            break;
        case ';':
        	{
        		alt7=3;
        	}
            break;
        case '{':
        	{
        		switch ( LA(2) )
        		{
        		case '}':
        			{
        				alt7=32;
        			}
        		    break;

        		default:
        		    alt7=4;
        		}

        	}
            break;
        case '}':
        	{
        		alt7=5;
        	}
            break;
        case '+':
        	{
        		alt7=6;
        	}
            break;
        case '-':
        	{
        		alt7=7;
        	}
            break;
        case '*':
        	{
        		alt7=8;
        	}
            break;
        case '/':
        	{
        		alt7=9;
        	}
            break;
        case ',':
        	{
        		alt7=10;
        	}
            break;
        case '=':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt7=19;
        			}
        		    break;

        		default:
        		    alt7=11;
        		}

        	}
            break;
        case 'd':
        	{
        		switch ( LA(2) )
        		{
        		case 'e':
        			{
        				switch ( LA(3) )
        				{
        				case 'f':
        					{
        						switch ( LA(4) )
        						{
        						case 'A':
        						case 'B':
        						case 'C':
        						case 'D':
        						case 'E':
        						case 'F':
        						case 'G':
        						case 'H':
        						case 'I':
        						case 'J':
        						case 'K':
        						case 'L':
        						case 'M':
        						case 'N':
        						case 'O':
        						case 'P':
        						case 'Q':
        						case 'R':
        						case 'S':
        						case 'T':
        						case 'U':
        						case 'V':
        						case 'W':
        						case 'X':
        						case 'Y':
        						case 'Z':
        						case 'a':
        						case 'b':
        						case 'c':
        						case 'd':
        						case 'e':
        						case 'f':
        						case 'g':
        						case 'h':
        						case 'i':
        						case 'j':
        						case 'k':
        						case 'l':
        						case 'm':
        						case 'n':
        						case 'o':
        						case 'p':
        						case 'q':
        						case 'r':
        						case 's':
        						case 't':
        						case 'u':
        						case 'v':
        						case 'w':
        						case 'x':
        						case 'y':
        						case 'z':
        							{
        								alt7=30;
        							}
        						    break;

        						default:
        						    alt7=12;
        						}

        					}
        				    break;

        				default:
        				    alt7=30;
        				}

        			}
        		    break;

        		default:
        		    alt7=30;
        		}

        	}
            break;
        case 'i':
        	{
        		switch ( LA(2) )
        		{
        		case 'f':
        			{
        				switch ( LA(3) )
        				{
        				case 'A':
        				case 'B':
        				case 'C':
        				case 'D':
        				case 'E':
        				case 'F':
        				case 'G':
        				case 'H':
        				case 'I':
        				case 'J':
        				case 'K':
        				case 'L':
        				case 'M':
        				case 'N':
        				case 'O':
        				case 'P':
        				case 'Q':
        				case 'R':
        				case 'S':
        				case 'T':
        				case 'U':
        				case 'V':
        				case 'W':
        				case 'X':
        				case 'Y':
        				case 'Z':
        				case 'a':
        				case 'b':
        				case 'c':
        				case 'd':
        				case 'e':
        				case 'f':
        				case 'g':
        				case 'h':
        				case 'i':
        				case 'j':
        				case 'k':
        				case 'l':
        				case 'm':
        				case 'n':
        				case 'o':
        				case 'p':
        				case 'q':
        				case 'r':
        				case 's':
        				case 't':
        				case 'u':
        				case 'v':
        				case 'w':
        				case 'x':
        				case 'y':
        				case 'z':
        					{
        						alt7=30;
        					}
        				    break;

        				default:
        				    alt7=13;
        				}

        			}
        		    break;

        		default:
        		    alt7=30;
        		}

        	}
            break;
        case 'e':
        	{
        		switch ( LA(2) )
        		{
        		case 'l':
        			{
        				switch ( LA(3) )
        				{
        				case 's':
        					{
        						switch ( LA(4) )
        						{
        						case 'e':
        							{
        								switch ( LA(5) )
        								{
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt7=30;
        									}
        								    break;

        								default:
        								    alt7=14;
        								}

        							}
        						    break;

        						default:
        						    alt7=30;
        						}

        					}
        				    break;

        				default:
        				    alt7=30;
        				}

        			}
        		    break;

        		default:
        		    alt7=30;
        		}

        	}
            break;
        case '>':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt7=16;
        			}
        		    break;

        		default:
        		    alt7=15;
        		}

        	}
            break;
        case '<':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt7=18;
        			}
        		    break;

        		default:
        		    alt7=17;
        		}

        	}
            break;
        case '!':
        	{
        		alt7=20;
        	}
            break;
        case '|':
        	{
        		switch ( LA(2) )
        		{
        		case '|':
        			{
        				alt7=21;
        			}
        		    break;

        		default:
        		    alt7=23;
        		}

        	}
            break;
        case '&':
        	{
        		switch ( LA(2) )
        		{
        		case '&':
        			{
        				alt7=22;
        			}
        		    break;

        		default:
        		    alt7=24;
        		}

        	}
            break;
        case 'p':
        	{
        		switch ( LA(2) )
        		{
        		case 'r':
        			{
        				switch ( LA(3) )
        				{
        				case 'i':
        					{
        						switch ( LA(4) )
        						{
        						case 'n':
        							{
        								switch ( LA(5) )
        								{
        								case 't':
        									{
        										switch ( LA(6) )
        										{
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt7=30;
        											}
        										    break;

        										default:
        										    alt7=25;
        										}

        									}
        								    break;

        								default:
        								    alt7=30;
        								}

        							}
        						    break;

        						default:
        						    alt7=30;
        						}

        					}
        				    break;

        				default:
        				    alt7=30;
        				}

        			}
        		    break;

        		default:
        		    alt7=30;
        		}

        	}
            break;
        case 'f':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'r':
        					{
        						switch ( LA(4) )
        						{
        						case 'A':
        						case 'B':
        						case 'C':
        						case 'D':
        						case 'E':
        						case 'F':
        						case 'G':
        						case 'H':
        						case 'I':
        						case 'J':
        						case 'K':
        						case 'L':
        						case 'M':
        						case 'N':
        						case 'O':
        						case 'P':
        						case 'Q':
        						case 'R':
        						case 'S':
        						case 'T':
        						case 'U':
        						case 'V':
        						case 'W':
        						case 'X':
        						case 'Y':
        						case 'Z':
        						case 'a':
        						case 'b':
        						case 'c':
        						case 'd':
        						case 'e':
        						case 'f':
        						case 'g':
        						case 'h':
        						case 'i':
        						case 'j':
        						case 'k':
        						case 'l':
        						case 'm':
        						case 'n':
        						case 'o':
        						case 'p':
        						case 'q':
        						case 'r':
        						case 's':
        						case 't':
        						case 'u':
        						case 'v':
        						case 'w':
        						case 'x':
        						case 'y':
        						case 'z':
        							{
        								alt7=30;
        							}
        						    break;

        						default:
        						    alt7=26;
        						}

        					}
        				    break;

        				default:
        				    alt7=30;
        				}

        			}
        		    break;

        		default:
        		    alt7=30;
        		}

        	}
            break;
        case 'w':
        	{
        		switch ( LA(2) )
        		{
        		case 'h':
        			{
        				switch ( LA(3) )
        				{
        				case 'i':
        					{
        						switch ( LA(4) )
        						{
        						case 'l':
        							{
        								switch ( LA(5) )
        								{
        								case 'e':
        									{
        										switch ( LA(6) )
        										{
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt7=30;
        											}
        										    break;

        										default:
        										    alt7=27;
        										}

        									}
        								    break;

        								default:
        								    alt7=30;
        								}

        							}
        						    break;

        						default:
        						    alt7=30;
        						}

        					}
        				    break;

        				default:
        				    alt7=30;
        				}

        			}
        		    break;

        		default:
        		    alt7=30;
        		}

        	}
            break;
        case 'b':
        	{
        		switch ( LA(2) )
        		{
        		case 'r':
        			{
        				switch ( LA(3) )
        				{
        				case 'e':
        					{
        						switch ( LA(4) )
        						{
        						case 'a':
        							{
        								switch ( LA(5) )
        								{
        								case 'k':
        									{
        										switch ( LA(6) )
        										{
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt7=30;
        											}
        										    break;

        										default:
        										    alt7=28;
        										}

        									}
        								    break;

        								default:
        								    alt7=30;
        								}

        							}
        						    break;

        						default:
        						    alt7=30;
        						}

        					}
        				    break;

        				default:
        				    alt7=30;
        				}

        			}
        		    break;

        		default:
        		    alt7=30;
        		}

        	}
            break;
        case 'c':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'n':
        					{
        						switch ( LA(4) )
        						{
        						case 't':
        							{
        								switch ( LA(5) )
        								{
        								case 'i':
        									{
        										switch ( LA(6) )
        										{
        										case 'n':
        											{
        												switch ( LA(7) )
        												{
        												case 'u':
        													{
        														switch ( LA(8) )
        														{
        														case 'e':
        															{
        																switch ( LA(9) )
        																{
        																case 'A':
        																case 'B':
        																case 'C':
        																case 'D':
        																case 'E':
        																case 'F':
        																case 'G':
        																case 'H':
        																case 'I':
        																case 'J':
        																case 'K':
        																case 'L':
        																case 'M':
        																case 'N':
        																case 'O':
        																case 'P':
        																case 'Q':
        																case 'R':
        																case 'S':
        																case 'T':
        																case 'U':
        																case 'V':
        																case 'W':
        																case 'X':
        																case 'Y':
        																case 'Z':
        																case 'a':
        																case 'b':
        																case 'c':
        																case 'd':
        																case 'e':
        																case 'f':
        																case 'g':
        																case 'h':
        																case 'i':
        																case 'j':
        																case 'k':
        																case 'l':
        																case 'm':
        																case 'n':
        																case 'o':
        																case 'p':
        																case 'q':
        																case 'r':
        																case 's':
        																case 't':
        																case 'u':
        																case 'v':
        																case 'w':
        																case 'x':
        																case 'y':
        																case 'z':
        																	{
        																		alt7=30;
        																	}
        																    break;

        																default:
        																    alt7=29;
        																}

        															}
        														    break;

        														default:
        														    alt7=30;
        														}

        													}
        												    break;

        												default:
        												    alt7=30;
        												}

        											}
        										    break;

        										default:
        										    alt7=30;
        										}

        									}
        								    break;

        								default:
        								    alt7=30;
        								}

        							}
        						    break;

        						default:
        						    alt7=30;
        						}

        					}
        				    break;

        				default:
        				    alt7=30;
        				}

        			}
        		    break;

        		default:
        		    alt7=30;
        		}

        	}
            break;
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case 'a':
        case 'g':
        case 'h':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'x':
        case 'y':
        case 'z':
        	{
        		alt7=30;
        	}
            break;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case '~':
        	{
        		alt7=31;
        	}
            break;
        case '\t':
        case '\n':
        case '\r':
        case ' ':
        	{
        		alt7=33;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 7;
            EXCEPTION->state        = 0;


            goto ruleTokensEx;

        }

        switch (alt7)
        {
    	case 1:
    	    // ./ExprCppTree.g:1:10: T__32
    	    {
    	        /* 1:10: T__32 */
    	        mT__32(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // ./ExprCppTree.g:1:16: T__33
    	    {
    	        /* 1:16: T__33 */
    	        mT__33(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // ./ExprCppTree.g:1:22: T__34
    	    {
    	        /* 1:22: T__34 */
    	        mT__34(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // ./ExprCppTree.g:1:28: T__35
    	    {
    	        /* 1:28: T__35 */
    	        mT__35(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // ./ExprCppTree.g:1:34: T__36
    	    {
    	        /* 1:34: T__36 */
    	        mT__36(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // ./ExprCppTree.g:1:40: PLUS
    	    {
    	        /* 1:40: PLUS */
    	        mPLUS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // ./ExprCppTree.g:1:45: MINUS
    	    {
    	        /* 1:45: MINUS */
    	        mMINUS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // ./ExprCppTree.g:1:51: TIMES
    	    {
    	        /* 1:51: TIMES */
    	        mTIMES(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // ./ExprCppTree.g:1:57: DIV
    	    {
    	        /* 1:57: DIV */
    	        mDIV(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // ./ExprCppTree.g:1:61: DOT
    	    {
    	        /* 1:61: DOT */
    	        mDOT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // ./ExprCppTree.g:1:65: ASSIGN
    	    {
    	        /* 1:65: ASSIGN */
    	        mASSIGN(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // ./ExprCppTree.g:1:72: DEF
    	    {
    	        /* 1:72: DEF */
    	        mDEF(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // ./ExprCppTree.g:1:76: IF
    	    {
    	        /* 1:76: IF */
    	        mIF(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // ./ExprCppTree.g:1:79: ELSE
    	    {
    	        /* 1:79: ELSE */
    	        mELSE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // ./ExprCppTree.g:1:84: GT
    	    {
    	        /* 1:84: GT */
    	        mGT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // ./ExprCppTree.g:1:87: GEQ
    	    {
    	        /* 1:87: GEQ */
    	        mGEQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // ./ExprCppTree.g:1:91: LS
    	    {
    	        /* 1:91: LS */
    	        mLS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // ./ExprCppTree.g:1:94: LEQ
    	    {
    	        /* 1:94: LEQ */
    	        mLEQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // ./ExprCppTree.g:1:98: EQ
    	    {
    	        /* 1:98: EQ */
    	        mEQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // ./ExprCppTree.g:1:101: NOT
    	    {
    	        /* 1:101: NOT */
    	        mNOT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // ./ExprCppTree.g:1:105: OR
    	    {
    	        /* 1:105: OR */
    	        mOR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // ./ExprCppTree.g:1:108: AND
    	    {
    	        /* 1:108: AND */
    	        mAND(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 23:
    	    // ./ExprCppTree.g:1:112: BITOR
    	    {
    	        /* 1:112: BITOR */
    	        mBITOR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 24:
    	    // ./ExprCppTree.g:1:118: BITAND
    	    {
    	        /* 1:118: BITAND */
    	        mBITAND(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 25:
    	    // ./ExprCppTree.g:1:125: PRINT
    	    {
    	        /* 1:125: PRINT */
    	        mPRINT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 26:
    	    // ./ExprCppTree.g:1:131: FOR
    	    {
    	        /* 1:131: FOR */
    	        mFOR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 27:
    	    // ./ExprCppTree.g:1:135: WHILE
    	    {
    	        /* 1:135: WHILE */
    	        mWHILE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 28:
    	    // ./ExprCppTree.g:1:141: BREAK
    	    {
    	        /* 1:141: BREAK */
    	        mBREAK(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 29:
    	    // ./ExprCppTree.g:1:147: CONTINUE
    	    {
    	        /* 1:147: CONTINUE */
    	        mCONTINUE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 30:
    	    // ./ExprCppTree.g:1:156: ID
    	    {
    	        /* 1:156: ID */
    	        mID(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 31:
    	    // ./ExprCppTree.g:1:159: INT
    	    {
    	        /* 1:159: INT */
    	        mINT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 32:
    	    // ./ExprCppTree.g:1:163: BLOCK
    	    {
    	        /* 1:163: BLOCK */
    	        mBLOCK(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 33:
    	    // ./ExprCppTree.g:1:169: WS
    	    {
    	        /* 1:169: WS */
    	        mWS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
