/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ./ExprCppTree.g
 *     -                            On : 2019-04-18 18:00:16
 *     -                for the parser : ExprCppTreeParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

    #include <assert.h>

/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ExprCppTreeParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pExprCppTreeParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pExprCppTreeParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pExprCppTreeParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pExprCppTreeParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   ExprCppTreeParserTokenNames[33+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "AND",
        (pANTLR3_UINT8) "ASSIGN",
        (pANTLR3_UINT8) "BITAND",
        (pANTLR3_UINT8) "BITOR",
        (pANTLR3_UINT8) "BLOCK",
        (pANTLR3_UINT8) "BREAK",
        (pANTLR3_UINT8) "CONTINUE",
        (pANTLR3_UINT8) "DEF",
        (pANTLR3_UINT8) "DIV",
        (pANTLR3_UINT8) "DOT",
        (pANTLR3_UINT8) "ELSE",
        (pANTLR3_UINT8) "EQ",
        (pANTLR3_UINT8) "FOR",
        (pANTLR3_UINT8) "GEQ",
        (pANTLR3_UINT8) "GT",
        (pANTLR3_UINT8) "ID",
        (pANTLR3_UINT8) "IF",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "LEQ",
        (pANTLR3_UINT8) "LS",
        (pANTLR3_UINT8) "MINUS",
        (pANTLR3_UINT8) "NOT",
        (pANTLR3_UINT8) "OR",
        (pANTLR3_UINT8) "PLUS",
        (pANTLR3_UINT8) "PRINT",
        (pANTLR3_UINT8) "TIMES",
        (pANTLR3_UINT8) "WHILE",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "';'",
        (pANTLR3_UINT8) "'{'",
        (pANTLR3_UINT8) "'}'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 ExprCppTreeParser_expr_return
	expr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_multExpr_return
	multExpr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_defExpr_return
	defExpr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_conditionExpr_return
	conditionExpr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_atom_return
	atom    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_stmt_return
	stmt    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_block_return
	block    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_prog_return
	prog    (pExprCppTreeParser ctx);
static void	ExprCppTreeParserFree(pExprCppTreeParser ctx);
static void     ExprCppTreeParserReset (pExprCppTreeParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "./ExprCppTree.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new ExprCppTreeParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pExprCppTreeParser
ExprCppTreeParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return ExprCppTreeParserNewSSD(instream, NULL);
}

/** \brief Create a new ExprCppTreeParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pExprCppTreeParser
ExprCppTreeParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pExprCppTreeParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pExprCppTreeParser) ANTLR3_CALLOC(1, sizeof(ExprCppTreeParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in ExprCppTreeParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our ExprCppTreeParser interface
     */
    ctx->expr	= expr;
    ctx->multExpr	= multExpr;
    ctx->defExpr	= defExpr;
    ctx->conditionExpr	= conditionExpr;
    ctx->atom	= atom;
    ctx->stmt	= stmt;
    ctx->block	= block;
    ctx->prog	= prog;
    ctx->free			= ExprCppTreeParserFree;
    ctx->reset			= ExprCppTreeParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);

ctx->vectors	= antlr3VectorFactoryNew(0);
    /* Install the token table
     */
    PSRSTATE->tokenNames   = ExprCppTreeParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
ExprCppTreeParserReset (pExprCppTreeParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 ExprCppTreeParserFree(pExprCppTreeParser ctx)
 {
    /* Free any scope memory
     */

ctx->vectors->close(ctx->vectors);
/* We created the adaptor so we must free it
 */
ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return ExprCppTreeParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multExpr_in_expr232  */
static	ANTLR3_BITWORD FOLLOW_multExpr_in_expr232_bits[]	= { ANTLR3_UINT64_LIT(0x0000000009000002) };
static  ANTLR3_BITSET_LIST FOLLOW_multExpr_in_expr232	= { FOLLOW_multExpr_in_expr232_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_expr236  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_expr236_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100280000) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_expr236	= { FOLLOW_PLUS_in_expr236_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MINUS_in_expr241  */
static	ANTLR3_BITWORD FOLLOW_MINUS_in_expr241_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100280000) };
static  ANTLR3_BITSET_LIST FOLLOW_MINUS_in_expr241	= { FOLLOW_MINUS_in_expr241_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multExpr_in_expr245  */
static	ANTLR3_BITWORD FOLLOW_multExpr_in_expr245_bits[]	= { ANTLR3_UINT64_LIT(0x0000000009000002) };
static  ANTLR3_BITSET_LIST FOLLOW_multExpr_in_expr245	= { FOLLOW_multExpr_in_expr245_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_expr255  */
static	ANTLR3_BITWORD FOLLOW_ID_in_expr255_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_expr255	= { FOLLOW_ID_in_expr255_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGN_in_expr257  */
static	ANTLR3_BITWORD FOLLOW_ASSIGN_in_expr257_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100280000) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGN_in_expr257	= { FOLLOW_ASSIGN_in_expr257_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_expr259  */
static	ANTLR3_BITWORD FOLLOW_expr_in_expr259_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_expr259	= { FOLLOW_expr_in_expr259_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multExpr285  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multExpr285_bits[]	= { ANTLR3_UINT64_LIT(0x0000000020001002) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multExpr285	= { FOLLOW_atom_in_multExpr285_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_multExpr288  */
static	ANTLR3_BITWORD FOLLOW_set_in_multExpr288_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100280000) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_multExpr288	= { FOLLOW_set_in_multExpr288_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multExpr297  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multExpr297_bits[]	= { ANTLR3_UINT64_LIT(0x0000000020001002) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multExpr297	= { FOLLOW_atom_in_multExpr297_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DEF_in_defExpr311  */
static	ANTLR3_BITWORD FOLLOW_DEF_in_defExpr311_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100280000) };
static  ANTLR3_BITSET_LIST FOLLOW_DEF_in_defExpr311	= { FOLLOW_DEF_in_defExpr311_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_defExpr313  */
static	ANTLR3_BITWORD FOLLOW_expr_in_defExpr313_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002002) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_defExpr313	= { FOLLOW_expr_in_defExpr313_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DOT_in_defExpr316  */
static	ANTLR3_BITWORD FOLLOW_DOT_in_defExpr316_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100280000) };
static  ANTLR3_BITSET_LIST FOLLOW_DOT_in_defExpr316	= { FOLLOW_DOT_in_defExpr316_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_defExpr318  */
static	ANTLR3_BITWORD FOLLOW_expr_in_defExpr318_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002002) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_defExpr318	= { FOLLOW_expr_in_defExpr318_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_conditionExpr348  */
static	ANTLR3_BITWORD FOLLOW_expr_in_conditionExpr348_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004C68012) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_conditionExpr348	= { FOLLOW_expr_in_conditionExpr348_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_conditionExpr351  */
static	ANTLR3_BITWORD FOLLOW_set_in_conditionExpr351_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100280000) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_conditionExpr351	= { FOLLOW_set_in_conditionExpr351_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_conditionExpr380  */
static	ANTLR3_BITWORD FOLLOW_expr_in_conditionExpr380_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004C68012) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_conditionExpr380	= { FOLLOW_expr_in_conditionExpr380_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_atom402  */
static	ANTLR3_BITWORD FOLLOW_INT_in_atom402_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_atom402	= { FOLLOW_INT_in_atom402_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_atom410  */
static	ANTLR3_BITWORD FOLLOW_ID_in_atom410_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_atom410	= { FOLLOW_ID_in_atom410_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_32_in_atom418  */
static	ANTLR3_BITWORD FOLLOW_32_in_atom418_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100280000) };
static  ANTLR3_BITSET_LIST FOLLOW_32_in_atom418	= { FOLLOW_32_in_atom418_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_atom421  */
static	ANTLR3_BITWORD FOLLOW_expr_in_atom421_bits[]	= { ANTLR3_UINT64_LIT(0x0000000200000000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_atom421	= { FOLLOW_expr_in_atom421_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_33_in_atom423  */
static	ANTLR3_BITWORD FOLLOW_33_in_atom423_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_33_in_atom423	= { FOLLOW_33_in_atom423_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_conditionExpr_in_stmt436  */
static	ANTLR3_BITWORD FOLLOW_conditionExpr_in_stmt436_bits[]	= { ANTLR3_UINT64_LIT(0x0000000400000000) };
static  ANTLR3_BITSET_LIST FOLLOW_conditionExpr_in_stmt436	= { FOLLOW_conditionExpr_in_stmt436_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_34_in_stmt437  */
static	ANTLR3_BITWORD FOLLOW_34_in_stmt437_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_34_in_stmt437	= { FOLLOW_34_in_stmt437_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_in_stmt448  */
static	ANTLR3_BITWORD FOLLOW_block_in_stmt448_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_block_in_stmt448	= { FOLLOW_block_in_stmt448_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_defExpr_in_stmt456  */
static	ANTLR3_BITWORD FOLLOW_defExpr_in_stmt456_bits[]	= { ANTLR3_UINT64_LIT(0x0000000400000000) };
static  ANTLR3_BITSET_LIST FOLLOW_defExpr_in_stmt456	= { FOLLOW_defExpr_in_stmt456_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_34_in_stmt457  */
static	ANTLR3_BITWORD FOLLOW_34_in_stmt457_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_34_in_stmt457	= { FOLLOW_34_in_stmt457_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_35_in_block470  */
static	ANTLR3_BITWORD FOLLOW_35_in_block470_bits[]	= { ANTLR3_UINT64_LIT(0x0000001900280800) };
static  ANTLR3_BITSET_LIST FOLLOW_35_in_block470	= { FOLLOW_35_in_block470_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_stmt_in_block472  */
static	ANTLR3_BITWORD FOLLOW_stmt_in_block472_bits[]	= { ANTLR3_UINT64_LIT(0x0000001900280800) };
static  ANTLR3_BITSET_LIST FOLLOW_stmt_in_block472	= { FOLLOW_stmt_in_block472_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_36_in_block475  */
static	ANTLR3_BITWORD FOLLOW_36_in_block475_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_36_in_block475	= { FOLLOW_36_in_block475_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_stmt_in_prog497  */
static	ANTLR3_BITWORD FOLLOW_stmt_in_prog497_bits[]	= { ANTLR3_UINT64_LIT(0x0000000900280802) };
static  ANTLR3_BITSET_LIST FOLLOW_stmt_in_prog497	= { FOLLOW_stmt_in_prog497_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start expr
 * ./ExprCppTree.g:42:1: expr : ( multExpr ( ( PLUS ^| MINUS ^) multExpr )* | ID ASSIGN expr -> ^( ASSIGN ID expr ) );
 */
static ExprCppTreeParser_expr_return
expr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_expr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    PLUS2;
    pANTLR3_COMMON_TOKEN    MINUS3;
    pANTLR3_COMMON_TOKEN    ID5;
    pANTLR3_COMMON_TOKEN    ASSIGN6;
    ExprCppTreeParser_multExpr_return multExpr1;
    #undef	RETURN_TYPE_multExpr1
    #define	RETURN_TYPE_multExpr1 ExprCppTreeParser_multExpr_return

    ExprCppTreeParser_multExpr_return multExpr4;
    #undef	RETURN_TYPE_multExpr4
    #define	RETURN_TYPE_multExpr4 ExprCppTreeParser_multExpr_return

    ExprCppTreeParser_expr_return expr7;
    #undef	RETURN_TYPE_expr7
    #define	RETURN_TYPE_expr7 ExprCppTreeParser_expr_return

    pANTLR3_BASE_TREE PLUS2_tree;
    pANTLR3_BASE_TREE MINUS3_tree;
    pANTLR3_BASE_TREE ID5_tree;
    pANTLR3_BASE_TREE ASSIGN6_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ID;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ASSIGN;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */

    root_0 = NULL;

    PLUS2       = NULL;
    MINUS3       = NULL;
    ID5       = NULL;
    ASSIGN6       = NULL;
    multExpr1.tree = NULL;

    multExpr4.tree = NULL;

    expr7.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    PLUS2_tree   = NULL;
    MINUS3_tree   = NULL;
    ID5_tree   = NULL;
    ASSIGN6_tree   = NULL;

    stream_ID   = NULL;
    #define CREATE_stream_ID  if (stream_ID == NULL) {stream_ID = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ID"); } 
    stream_ASSIGN   = NULL;
    #define CREATE_stream_ASSIGN  if (stream_ASSIGN == NULL) {stream_ASSIGN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ASSIGN"); } 
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;

    {
        {
            //  ./ExprCppTree.g:42:5: ( multExpr ( ( PLUS ^| MINUS ^) multExpr )* | ID ASSIGN expr -> ^( ASSIGN ID expr ) )

            ANTLR3_UINT32 alt3;

            alt3=2;

            switch ( LA(1) )
            {
            case INT:
            case 32:
            	{
            		alt3=1;
            	}
                break;
            case ID:
            	{
            		switch ( LA(2) )
            		{
            		case ASSIGN:
            			{
            				alt3=2;
            			}
            		    break;
            		case AND:
            		case DIV:
            		case DOT:
            		case EQ:
            		case GEQ:
            		case GT:
            		case LEQ:
            		case LS:
            		case MINUS:
            		case OR:
            		case PLUS:
            		case TIMES:
            		case 33:
            		case 34:
            			{
            				alt3=1;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 3;
            		    EXCEPTION->state        = 2;


            		    goto ruleexprEx;

            		}

            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 3;
                EXCEPTION->state        = 0;


                goto ruleexprEx;

            }

            switch (alt3)
            {
        	case 1:
        	    // ./ExprCppTree.g:42:7: multExpr ( ( PLUS ^| MINUS ^) multExpr )*
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_multExpr_in_expr232);
        	        multExpr1=multExpr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, multExpr1.tree);

        	        // ./ExprCppTree.g:42:16: ( ( PLUS ^| MINUS ^) multExpr )*

        	        for (;;)
        	        {
        	            int alt2=2;
        	            switch ( LA(1) )
        	            {
        	            case MINUS:
        	            case PLUS:
        	            	{
        	            		alt2=1;
        	            	}
        	                break;

        	            }

        	            switch (alt2)
        	            {
        	        	case 1:
        	        	    // ./ExprCppTree.g:42:17: ( PLUS ^| MINUS ^) multExpr
        	        	    {
        	        	        // ./ExprCppTree.g:42:17: ( PLUS ^| MINUS ^)
        	        	        {
        	        	            int alt1=2;
        	        	            switch ( LA(1) )
        	        	            {
        	        	            case PLUS:
        	        	            	{
        	        	            		alt1=1;
        	        	            	}
        	        	                break;
        	        	            case MINUS:
        	        	            	{
        	        	            		alt1=2;
        	        	            	}
        	        	                break;

        	        	            default:
        	        	                CONSTRUCTEX();
        	        	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        	        	                EXCEPTION->message      = (void *)"";
        	        	                EXCEPTION->decisionNum  = 1;
        	        	                EXCEPTION->state        = 0;


        	        	                goto ruleexprEx;

        	        	            }

        	        	            switch (alt1)
        	        	            {
        	        	        	case 1:
        	        	        	    // ./ExprCppTree.g:42:18: PLUS ^
        	        	        	    {
        	        	        	        PLUS2 = (pANTLR3_COMMON_TOKEN) MATCHT(PLUS, &FOLLOW_PLUS_in_expr236);
        	        	        	        if  (HASEXCEPTION())
        	        	        	        {
        	        	        	            goto ruleexprEx;
        	        	        	        }

        	        	        	        PLUS2_tree = 
        	        	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, PLUS2))
        	        	        	        ;
        	        	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, PLUS2_tree, root_0));


        	        	        	    }
        	        	        	    break;
        	        	        	case 2:
        	        	        	    // ./ExprCppTree.g:42:26: MINUS ^
        	        	        	    {
        	        	        	        MINUS3 = (pANTLR3_COMMON_TOKEN) MATCHT(MINUS, &FOLLOW_MINUS_in_expr241);
        	        	        	        if  (HASEXCEPTION())
        	        	        	        {
        	        	        	            goto ruleexprEx;
        	        	        	        }

        	        	        	        MINUS3_tree = 
        	        	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, MINUS3))
        	        	        	        ;
        	        	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, MINUS3_tree, root_0));


        	        	        	    }
        	        	        	    break;

        	        	            }
        	        	        }

        	        	        FOLLOWPUSH(FOLLOW_multExpr_in_expr245);
        	        	        multExpr4=multExpr(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleexprEx;
        	        	        }

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, multExpr4.tree);

        	        	    }
        	        	    break;

        	        	default:
        	        	    goto loop2;	/* break out of the loop */
        	        	    break;
        	            }
        	        }
        	        loop2: ; /* Jump out to here if this rule does not match */


        	    }
        	    break;
        	case 2:
        	    // ./ExprCppTree.g:43:7: ID ASSIGN expr
        	    {
        	        ID5 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_expr255);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }
        	         
        	        CREATE_stream_ID; stream_ID->add(stream_ID, ID5, NULL);


        	        ASSIGN6 = (pANTLR3_COMMON_TOKEN) MATCHT(ASSIGN, &FOLLOW_ASSIGN_in_expr257);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }
        	         
        	        CREATE_stream_ASSIGN; stream_ASSIGN->add(stream_ASSIGN, ASSIGN6, NULL);


        	        FOLLOWPUSH(FOLLOW_expr_in_expr259);
        	        expr7=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr7.tree, NULL);

        	        /* AST REWRITE
        	         * elements          : ASSIGN, ID, expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 43:22: -> ^( ASSIGN ID expr )
        	        	{
        	        	    // ./ExprCppTree.g:43:25: ^( ASSIGN ID expr )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
        	        	        stream_ASSIGN == NULL ? NULL : stream_ASSIGN->nextNode(stream_ASSIGN)
        	        	        , root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, 
        	        	        stream_ID == NULL ? NULL : stream_ID->nextNode(stream_ID)
        	        	        );

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_ID != NULL) stream_ID->free(stream_ID);
        if (stream_ASSIGN != NULL) stream_ASSIGN->free(stream_ASSIGN);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end expr */

/**
 * $ANTLR start multExpr
 * ./ExprCppTree.g:45:1: multExpr : atom ( ( TIMES | DIV ) ^ atom )* ;
 */
static ExprCppTreeParser_multExpr_return
multExpr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_multExpr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set9;
    ExprCppTreeParser_atom_return atom8;
    #undef	RETURN_TYPE_atom8
    #define	RETURN_TYPE_atom8 ExprCppTreeParser_atom_return

    ExprCppTreeParser_atom_return atom10;
    #undef	RETURN_TYPE_atom10
    #define	RETURN_TYPE_atom10 ExprCppTreeParser_atom_return

    pANTLR3_BASE_TREE set9_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    set9       = NULL;
    atom8.tree = NULL;

    atom10.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    set9_tree   = NULL;


    retval.tree  = NULL;

    {
        // ./ExprCppTree.g:46:5: ( atom ( ( TIMES | DIV ) ^ atom )* )
        // ./ExprCppTree.g:46:7: atom ( ( TIMES | DIV ) ^ atom )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_atom_in_multExpr285);
            atom8=atom(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemultExprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, atom8.tree);

            // ./ExprCppTree.g:46:12: ( ( TIMES | DIV ) ^ atom )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) )
                {
                case DIV:
                case TIMES:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4)
                {
            	case 1:
            	    // ./ExprCppTree.g:46:13: ( TIMES | DIV ) ^ atom
            	    {
            	        set9=(pANTLR3_COMMON_TOKEN)LT(1);

            	        set9=(pANTLR3_COMMON_TOKEN)LT(1);

            	        if ( LA(1) == DIV || LA(1) == TIMES )
            	        {
            	            CONSUME();
            	            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
            	            (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set9))
            	            , root_0));
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = NULL;

            	            goto rulemultExprEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_atom_in_multExpr297);
            	        atom10=atom(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemultExprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, atom10.tree);

            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto rulemultExprEx; /* Prevent compiler warnings */
    rulemultExprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end multExpr */

/**
 * $ANTLR start defExpr
 * ./ExprCppTree.g:49:1: defExpr : DEF expr ( DOT expr )* -> ^( DEF ( expr )+ ) ;
 */
static ExprCppTreeParser_defExpr_return
defExpr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_defExpr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    DEF11;
    pANTLR3_COMMON_TOKEN    DOT13;
    ExprCppTreeParser_expr_return expr12;
    #undef	RETURN_TYPE_expr12
    #define	RETURN_TYPE_expr12 ExprCppTreeParser_expr_return

    ExprCppTreeParser_expr_return expr14;
    #undef	RETURN_TYPE_expr14
    #define	RETURN_TYPE_expr14 ExprCppTreeParser_expr_return

    pANTLR3_BASE_TREE DEF11_tree;
    pANTLR3_BASE_TREE DOT13_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_DEF;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_DOT;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */

    root_0 = NULL;

    DEF11       = NULL;
    DOT13       = NULL;
    expr12.tree = NULL;

    expr14.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    DEF11_tree   = NULL;
    DOT13_tree   = NULL;

    stream_DEF   = NULL;
    #define CREATE_stream_DEF  if (stream_DEF == NULL) {stream_DEF = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token DEF"); } 
    stream_DOT   = NULL;
    #define CREATE_stream_DOT  if (stream_DOT == NULL) {stream_DOT = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token DOT"); } 
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;

    {
        // ./ExprCppTree.g:49:8: ( DEF expr ( DOT expr )* -> ^( DEF ( expr )+ ) )
        // ./ExprCppTree.g:49:10: DEF expr ( DOT expr )*
        {
            DEF11 = (pANTLR3_COMMON_TOKEN) MATCHT(DEF, &FOLLOW_DEF_in_defExpr311);
            if  (HASEXCEPTION())
            {
                goto ruledefExprEx;
            }
             
            CREATE_stream_DEF; stream_DEF->add(stream_DEF, DEF11, NULL);


            FOLLOWPUSH(FOLLOW_expr_in_defExpr313);
            expr12=expr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruledefExprEx;
            }

            CREATE_stream_expr; stream_expr->add(stream_expr, expr12.tree, NULL);

            // ./ExprCppTree.g:49:19: ( DOT expr )*

            for (;;)
            {
                int alt5=2;
                switch ( LA(1) )
                {
                case DOT:
                	{
                		alt5=1;
                	}
                    break;

                }

                switch (alt5)
                {
            	case 1:
            	    // ./ExprCppTree.g:49:20: DOT expr
            	    {
            	        DOT13 = (pANTLR3_COMMON_TOKEN) MATCHT(DOT, &FOLLOW_DOT_in_defExpr316);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledefExprEx;
            	        }
            	         
            	        CREATE_stream_DOT; stream_DOT->add(stream_DOT, DOT13, NULL);


            	        FOLLOWPUSH(FOLLOW_expr_in_defExpr318);
            	        expr14=expr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledefExprEx;
            	        }

            	        CREATE_stream_expr; stream_expr->add(stream_expr, expr14.tree, NULL);

            	    }
            	    break;

            	default:
            	    goto loop5;	/* break out of the loop */
            	    break;
                }
            }
            loop5: ; /* Jump out to here if this rule does not match */


            /* AST REWRITE
             * elements          : DEF, expr
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 49:31: -> ^( DEF ( expr )+ )
            	{
            	    // ./ExprCppTree.g:49:34: ^( DEF ( expr )+ )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
            	        stream_DEF == NULL ? NULL : stream_DEF->nextNode(stream_DEF)
            	        , root_1));

            	        if ((stream_expr == NULL || !stream_expr->hasNext(stream_expr))  )
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_REWRITE_EARLY_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_REWRITE_EARLY_EXCEPTION_NAME;
            	        }
            	        else
            	        {
            	        	while ( (stream_expr->hasNext(stream_expr))  ) {
            	        		ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

            	        	}
            	        	stream_expr->reset(stream_expr);

            	        }
            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}


            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }

    // This is where rules clean up and exit
    //
    goto ruledefExprEx; /* Prevent compiler warnings */
    ruledefExprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_DEF != NULL) stream_DEF->free(stream_DEF);
        if (stream_DOT != NULL) stream_DOT->free(stream_DOT);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end defExpr */

/**
 * $ANTLR start conditionExpr
 * ./ExprCppTree.g:50:1: conditionExpr : expr ( ( GT | GEQ | LS | LEQ | OR | AND | EQ ) ^ expr )* ;
 */
static ExprCppTreeParser_conditionExpr_return
conditionExpr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_conditionExpr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set16;
    ExprCppTreeParser_expr_return expr15;
    #undef	RETURN_TYPE_expr15
    #define	RETURN_TYPE_expr15 ExprCppTreeParser_expr_return

    ExprCppTreeParser_expr_return expr17;
    #undef	RETURN_TYPE_expr17
    #define	RETURN_TYPE_expr17 ExprCppTreeParser_expr_return

    pANTLR3_BASE_TREE set16_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    set16       = NULL;
    expr15.tree = NULL;

    expr17.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    set16_tree   = NULL;


    retval.tree  = NULL;

    {
        // ./ExprCppTree.g:50:14: ( expr ( ( GT | GEQ | LS | LEQ | OR | AND | EQ ) ^ expr )* )
        // ./ExprCppTree.g:51:13: expr ( ( GT | GEQ | LS | LEQ | OR | AND | EQ ) ^ expr )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_expr_in_conditionExpr348);
            expr15=expr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleconditionExprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, expr15.tree);

            // ./ExprCppTree.g:51:18: ( ( GT | GEQ | LS | LEQ | OR | AND | EQ ) ^ expr )*

            for (;;)
            {
                int alt6=2;
                switch ( LA(1) )
                {
                case AND:
                case EQ:
                case GEQ:
                case GT:
                case LEQ:
                case LS:
                case OR:
                	{
                		alt6=1;
                	}
                    break;

                }

                switch (alt6)
                {
            	case 1:
            	    // ./ExprCppTree.g:51:19: ( GT | GEQ | LS | LEQ | OR | AND | EQ ) ^ expr
            	    {
            	        set16=(pANTLR3_COMMON_TOKEN)LT(1);

            	        set16=(pANTLR3_COMMON_TOKEN)LT(1);

            	        if ( LA(1) == AND || LA(1) == EQ || ((LA(1) >= GEQ) && (LA(1) <= GT)) || ((LA(1) >= LEQ) && (LA(1) <= LS)) || LA(1) == OR )
            	        {
            	            CONSUME();
            	            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
            	            (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set16))
            	            , root_0));
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = NULL;

            	            goto ruleconditionExprEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_expr_in_conditionExpr380);
            	        expr17=expr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleconditionExprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, expr17.tree);

            	    }
            	    break;

            	default:
            	    goto loop6;	/* break out of the loop */
            	    break;
                }
            }
            loop6: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleconditionExprEx; /* Prevent compiler warnings */
    ruleconditionExprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end conditionExpr */

/**
 * $ANTLR start atom
 * ./ExprCppTree.g:54:1: atom : ( INT | ID | '(' ! expr ')' !);
 */
static ExprCppTreeParser_atom_return
atom(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_atom_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    INT18;
    pANTLR3_COMMON_TOKEN    ID19;
    pANTLR3_COMMON_TOKEN    char_literal20;
    pANTLR3_COMMON_TOKEN    char_literal22;
    ExprCppTreeParser_expr_return expr21;
    #undef	RETURN_TYPE_expr21
    #define	RETURN_TYPE_expr21 ExprCppTreeParser_expr_return

    pANTLR3_BASE_TREE INT18_tree;
    pANTLR3_BASE_TREE ID19_tree;
    pANTLR3_BASE_TREE char_literal20_tree;
    pANTLR3_BASE_TREE char_literal22_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    INT18       = NULL;
    ID19       = NULL;
    char_literal20       = NULL;
    char_literal22       = NULL;
    expr21.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    INT18_tree   = NULL;
    ID19_tree   = NULL;
    char_literal20_tree   = NULL;
    char_literal22_tree   = NULL;


    retval.tree  = NULL;

    {
        {
            //  ./ExprCppTree.g:54:5: ( INT | ID | '(' ! expr ')' !)

            ANTLR3_UINT32 alt7;

            alt7=3;

            switch ( LA(1) )
            {
            case INT:
            	{
            		alt7=1;
            	}
                break;
            case ID:
            	{
            		alt7=2;
            	}
                break;
            case 32:
            	{
            		alt7=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 7;
                EXCEPTION->state        = 0;


                goto ruleatomEx;

            }

            switch (alt7)
            {
        	case 1:
        	    // ./ExprCppTree.g:54:7: INT
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        INT18 = (pANTLR3_COMMON_TOKEN) MATCHT(INT, &FOLLOW_INT_in_atom402);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        INT18_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, INT18));
        	        ADAPTOR->addChild(ADAPTOR, root_0, INT18_tree);


        	    }
        	    break;
        	case 2:
        	    // ./ExprCppTree.g:55:7: ID
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        ID19 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_atom410);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ID19_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ID19));
        	        ADAPTOR->addChild(ADAPTOR, root_0, ID19_tree);


        	    }
        	    break;
        	case 3:
        	    // ./ExprCppTree.g:56:7: '(' ! expr ')' !
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        char_literal20 = (pANTLR3_COMMON_TOKEN) MATCHT(32, &FOLLOW_32_in_atom418);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_expr_in_atom421);
        	        expr21=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, expr21.tree);

        	        char_literal22 = (pANTLR3_COMMON_TOKEN) MATCHT(33, &FOLLOW_33_in_atom423);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleatomEx; /* Prevent compiler warnings */
    ruleatomEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end atom */

/**
 * $ANTLR start stmt
 * ./ExprCppTree.g:59:1: stmt : ( conditionExpr ';' !| block | defExpr ';' !);
 */
static ExprCppTreeParser_stmt_return
stmt(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_stmt_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal24;
    pANTLR3_COMMON_TOKEN    char_literal27;
    ExprCppTreeParser_conditionExpr_return conditionExpr23;
    #undef	RETURN_TYPE_conditionExpr23
    #define	RETURN_TYPE_conditionExpr23 ExprCppTreeParser_conditionExpr_return

    ExprCppTreeParser_block_return block25;
    #undef	RETURN_TYPE_block25
    #define	RETURN_TYPE_block25 ExprCppTreeParser_block_return

    ExprCppTreeParser_defExpr_return defExpr26;
    #undef	RETURN_TYPE_defExpr26
    #define	RETURN_TYPE_defExpr26 ExprCppTreeParser_defExpr_return

    pANTLR3_BASE_TREE char_literal24_tree;
    pANTLR3_BASE_TREE char_literal27_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal24       = NULL;
    char_literal27       = NULL;
    conditionExpr23.tree = NULL;

    block25.tree = NULL;

    defExpr26.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal24_tree   = NULL;
    char_literal27_tree   = NULL;


    retval.tree  = NULL;

    {
        {
            //  ./ExprCppTree.g:59:5: ( conditionExpr ';' !| block | defExpr ';' !)

            ANTLR3_UINT32 alt8;

            alt8=3;

            switch ( LA(1) )
            {
            case ID:
            case INT:
            case 32:
            	{
            		alt8=1;
            	}
                break;
            case 35:
            	{
            		alt8=2;
            	}
                break;
            case DEF:
            	{
            		alt8=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 8;
                EXCEPTION->state        = 0;


                goto rulestmtEx;

            }

            switch (alt8)
            {
        	case 1:
        	    // ./ExprCppTree.g:59:7: conditionExpr ';' !
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_conditionExpr_in_stmt436);
        	        conditionExpr23=conditionExpr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, conditionExpr23.tree);

        	        char_literal24 = (pANTLR3_COMMON_TOKEN) MATCHT(34, &FOLLOW_34_in_stmt437);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // ./ExprCppTree.g:60:7: block
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_block_in_stmt448);
        	        block25=block(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, block25.tree);

        	    }
        	    break;
        	case 3:
        	    // ./ExprCppTree.g:61:7: defExpr ';' !
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_defExpr_in_stmt456);
        	        defExpr26=defExpr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, defExpr26.tree);

        	        char_literal27 = (pANTLR3_COMMON_TOKEN) MATCHT(34, &FOLLOW_34_in_stmt457);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulestmtEx; /* Prevent compiler warnings */
    rulestmtEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end stmt */

/**
 * $ANTLR start block
 * ./ExprCppTree.g:64:1: block : '{' ( stmt )* '}' -> ^( BLOCK ( stmt )* ) ;
 */
static ExprCppTreeParser_block_return
block(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_block_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal28;
    pANTLR3_COMMON_TOKEN    char_literal30;
    ExprCppTreeParser_stmt_return stmt29;
    #undef	RETURN_TYPE_stmt29
    #define	RETURN_TYPE_stmt29 ExprCppTreeParser_stmt_return

    pANTLR3_BASE_TREE char_literal28_tree;
    pANTLR3_BASE_TREE char_literal30_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_35;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_36;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_stmt;
    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal28       = NULL;
    char_literal30       = NULL;
    stmt29.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal28_tree   = NULL;
    char_literal30_tree   = NULL;

    stream_35   = NULL;
    #define CREATE_stream_35  if (stream_35 == NULL) {stream_35 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 35"); } 
    stream_36   = NULL;
    #define CREATE_stream_36  if (stream_36 == NULL) {stream_36 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 36"); } 
    stream_stmt   = NULL;
    #define CREATE_stream_stmt  if (stream_stmt == NULL) {stream_stmt = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule stmt"); }

    retval.tree  = NULL;

    {
        // ./ExprCppTree.g:64:6: ( '{' ( stmt )* '}' -> ^( BLOCK ( stmt )* ) )
        // ./ExprCppTree.g:64:8: '{' ( stmt )* '}'
        {
            char_literal28 = (pANTLR3_COMMON_TOKEN) MATCHT(35, &FOLLOW_35_in_block470);
            if  (HASEXCEPTION())
            {
                goto ruleblockEx;
            }
             
            CREATE_stream_35; stream_35->add(stream_35, char_literal28, NULL);


            // ./ExprCppTree.g:64:12: ( stmt )*

            for (;;)
            {
                int alt9=2;
                switch ( LA(1) )
                {
                case DEF:
                case ID:
                case INT:
                case 32:
                case 35:
                	{
                		alt9=1;
                	}
                    break;

                }

                switch (alt9)
                {
            	case 1:
            	    // ./ExprCppTree.g:64:12: stmt
            	    {
            	        FOLLOWPUSH(FOLLOW_stmt_in_block472);
            	        stmt29=stmt(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleblockEx;
            	        }

            	        CREATE_stream_stmt; stream_stmt->add(stream_stmt, stmt29.tree, NULL);

            	    }
            	    break;

            	default:
            	    goto loop9;	/* break out of the loop */
            	    break;
                }
            }
            loop9: ; /* Jump out to here if this rule does not match */


            char_literal30 = (pANTLR3_COMMON_TOKEN) MATCHT(36, &FOLLOW_36_in_block475);
            if  (HASEXCEPTION())
            {
                goto ruleblockEx;
            }
             
            CREATE_stream_36; stream_36->add(stream_36, char_literal30, NULL);


            /* AST REWRITE
             * elements          : stmt
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 64:22: -> ^( BLOCK ( stmt )* )
            	{
            	    // ./ExprCppTree.g:64:25: ^( BLOCK ( stmt )* )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
            	        (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, BLOCK, (pANTLR3_UINT8)"BLOCK")
            	        , root_1));

            	        // ./ExprCppTree.g:64:33: ( stmt )*
            	        {
            	        	while ( (stream_stmt != NULL && stream_stmt->hasNext(stream_stmt))  )
            	        	{
            	        		ADAPTOR->addChild(ADAPTOR, root_1, stream_stmt == NULL ? NULL : stream_stmt->nextTree(stream_stmt));

            	        	}
            	        	if (stream_stmt != NULL) stream_stmt->reset(stream_stmt);

            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}


            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }

    // This is where rules clean up and exit
    //
    goto ruleblockEx; /* Prevent compiler warnings */
    ruleblockEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_35 != NULL) stream_35->free(stream_35);
        if (stream_36 != NULL) stream_36->free(stream_36);
        if (stream_stmt != NULL) stream_stmt->free(stream_stmt);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end block */

/**
 * $ANTLR start prog
 * ./ExprCppTree.g:66:1: prog : ( stmt )+ ;
 */
static ExprCppTreeParser_prog_return
prog(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_prog_return retval;


    pANTLR3_BASE_TREE root_0;

    ExprCppTreeParser_stmt_return stmt31;
    #undef	RETURN_TYPE_stmt31
    #define	RETURN_TYPE_stmt31 ExprCppTreeParser_stmt_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    stmt31.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // ./ExprCppTree.g:67:5: ( ( stmt )+ )
        // ./ExprCppTree.g:67:7: ( stmt )+
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // ./ExprCppTree.g:67:7: ( stmt )+
            {
                int cnt10=0;

                for (;;)
                {
                    int alt10=2;
            	switch ( LA(1) )
            	{
            	case DEF:
            	case ID:
            	case INT:
            	case 32:
            	case 35:
            		{
            			alt10=1;
            		}
            	    break;

            	}

            	switch (alt10)
            	{
            	    case 1:
            	        // ./ExprCppTree.g:67:8: stmt
            	        {
            	            FOLLOWPUSH(FOLLOW_stmt_in_prog497);
            	            stmt31=stmt(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleprogEx;
            	            }

            	            ADAPTOR->addChild(ADAPTOR, root_0, stmt31.tree);

            	            {
            	                pANTLR3_STRING s = (stmt31.tree)->toStringTree((stmt31.tree));
            	                             assert(s->chars);
            	                             printf(" tree %s\n", s->chars);
            	                            
            	            }


            	        }
            	        break;

            	    default:

            		if ( cnt10 >= 1 )
            		{
            		    goto loop10;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleprogEx;
            	}
            	cnt10++;
                }
                loop10: ;	/* Jump to here if this rule does not match */
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprogEx; /* Prevent compiler warnings */
    ruleprogEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end prog */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
