/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ./ExprCppTree.g
 *     -                            On : 2019-04-23 18:20:46
 *     -                 for the lexer : ExprCppTreeLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
ExprCppTreeLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pExprCppTreeLexer, which is returned from a call to ExprCppTreeLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pExprCppTreeLexer are  as follows:
 *
 *  - 
 void
      pExprCppTreeLexer->T__36(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->T__37(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->T__38(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->T__39(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->T__40(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->T__41(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->PLUS(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->MINUS(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->TIMES(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->DIV(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->DOT(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->ASSIGN(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->DEF(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->IF(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->ELSE(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->GT(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->GEQ(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->LS(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->LEQ(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->EQ(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->NOT(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OR(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->AND(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->BITOR(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->BITAND(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->PRINT(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->FOR(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->WHILE(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->SWITCH(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->CASE(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->DEFAULT(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->BREAK(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->CONTINUE(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->ID(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->INT(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->STRING(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->BLOCK(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->WS(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->Tokens(pExprCppTreeLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_ExprCppTreeLexer_H
#define _ExprCppTreeLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct ExprCppTreeLexer_Ctx_struct ExprCppTreeLexer, * pExprCppTreeLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
ExprCppTreeLexer

 */
struct ExprCppTreeLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__36)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mT__37)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mT__38)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mT__39)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mT__40)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mT__41)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mPLUS)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mMINUS)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mTIMES)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mDIV)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mDOT)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mASSIGN)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mDEF)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mIF)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mELSE)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mGT)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mGEQ)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mLS)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mLEQ)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mEQ)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mNOT)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOR)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mAND)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mBITOR)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mBITAND)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mPRINT)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mFOR)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mWHILE)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mSWITCH)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mCASE)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mDEFAULT)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mBREAK)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mCONTINUE)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mID)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mINT)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mSTRING)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mBLOCK)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct ExprCppTreeLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct ExprCppTreeLexer_Ctx_struct * ctx);
    void	    (*free)   (struct ExprCppTreeLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pExprCppTreeLexer ExprCppTreeLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pExprCppTreeLexer ExprCppTreeLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__36      36
#define T__37      37
#define T__38      38
#define T__39      39
#define T__40      40
#define T__41      41
#define AND      4
#define ASSIGN      5
#define BITAND      6
#define BITOR      7
#define BLOCK      8
#define BREAK      9
#define CASE      10
#define CONTINUE      11
#define DEF      12
#define DEFAULT      13
#define DIV      14
#define DOT      15
#define ELSE      16
#define EQ      17
#define FOR      18
#define GEQ      19
#define GT      20
#define ID      21
#define IF      22
#define INT      23
#define LEQ      24
#define LS      25
#define MINUS      26
#define NOT      27
#define OR      28
#define PLUS      29
#define PRINT      30
#define STRING      31
#define SWITCH      32
#define TIMES      33
#define WHILE      34
#define WS      35
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for ExprCppTreeLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
