/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ./ExprCppTree.g
 *     -                            On : 2019-04-25 10:24:19
 *     -                 for the lexer : ExprCppTreeLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ExprCppTreeLexer.h"
/* ----------------------------------------- */


/** String literals used by ExprCppTreeLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x64, 0x65, 0x66,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x69, 0x66,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x65, 0x6C, 0x73, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x3E, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x3C, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x3D, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x7C, 0x7C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x26, 0x26,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x70, 0x72, 0x69, 0x6E, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x66, 0x6F, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x77, 0x68, 0x69, 0x6C, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x73, 0x77, 0x69, 0x74, 0x63, 0x68,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_13[]  = { 0x63, 0x61, 0x73, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_14[]  = { 0x64, 0x65, 0x66, 0x61, 0x75, 0x6C, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_15[]  = { 0x62, 0x72, 0x65, 0x61, 0x6B,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_16[]  = { 0x63, 0x6F, 0x6E, 0x74, 0x69, 0x6E, 0x75, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_17[]  = { 0x7B, 0x7D,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pExprCppTreeLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pExprCppTreeLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pExprCppTreeLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pExprCppTreeLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mT__36    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mT__37    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mT__38    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mT__39    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mT__40    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mT__41    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mPLUS    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mMINUS    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mTIMES    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mDIV    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mDOT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mASSIGN    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mDEF    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mIF    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mELSE    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mGT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mGEQ    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mLS    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mLEQ    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mEQ    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mNOT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOR    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mAND    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mBITOR    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mBITAND    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mPRINT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mFOR    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mWHILE    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mSWITCH    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mCASE    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mDEFAULT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mBREAK    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mCONTINUE    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mID    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mINT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mSTRING    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mBLOCK    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mWS    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pExprCppTreeLexer ctx);
static void	ExprCppTreeLexerFree(pExprCppTreeLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
ExprCppTreeLexerFree  (pExprCppTreeLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
ExprCppTreeLexerReset (pExprCppTreeLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "./ExprCppTree.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called ExprCppTreeLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pExprCppTreeLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pExprCppTreeLexer ExprCppTreeLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return ExprCppTreeLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called ExprCppTreeLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pExprCppTreeLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pExprCppTreeLexer ExprCppTreeLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pExprCppTreeLexer ctx; // Context structure we will build and return

    ctx = (pExprCppTreeLexer) ANTLR3_CALLOC(1, sizeof(ExprCppTreeLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in ExprCppTreeLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our ExprCppTreeLexer interface
     */
    ctx->mT__36	= mT__36;
    ctx->mT__37	= mT__37;
    ctx->mT__38	= mT__38;
    ctx->mT__39	= mT__39;
    ctx->mT__40	= mT__40;
    ctx->mT__41	= mT__41;
    ctx->mPLUS	= mPLUS;
    ctx->mMINUS	= mMINUS;
    ctx->mTIMES	= mTIMES;
    ctx->mDIV	= mDIV;
    ctx->mDOT	= mDOT;
    ctx->mASSIGN	= mASSIGN;
    ctx->mDEF	= mDEF;
    ctx->mIF	= mIF;
    ctx->mELSE	= mELSE;
    ctx->mGT	= mGT;
    ctx->mGEQ	= mGEQ;
    ctx->mLS	= mLS;
    ctx->mLEQ	= mLEQ;
    ctx->mEQ	= mEQ;
    ctx->mNOT	= mNOT;
    ctx->mOR	= mOR;
    ctx->mAND	= mAND;
    ctx->mBITOR	= mBITOR;
    ctx->mBITAND	= mBITAND;
    ctx->mPRINT	= mPRINT;
    ctx->mFOR	= mFOR;
    ctx->mWHILE	= mWHILE;
    ctx->mSWITCH	= mSWITCH;
    ctx->mCASE	= mCASE;
    ctx->mDEFAULT	= mDEFAULT;
    ctx->mBREAK	= mBREAK;
    ctx->mCONTINUE	= mCONTINUE;
    ctx->mID	= mID;
    ctx->mINT	= mINT;
    ctx->mSTRING	= mSTRING;
    ctx->mBLOCK	= mBLOCK;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= ExprCppTreeLexerFree;
    ctx->reset          = ExprCppTreeLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:7: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__36
 *
 * Looks to match the characters the constitute the token T__36
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__36(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__36;


    // ./ExprCppTree.g:7:7: ( '(' )
    // ./ExprCppTree.g:7:9: '('
    {
        MATCHC('(');
        if  (HASEXCEPTION())
        {
            goto ruleT__36Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__36Ex; /* Prevent compiler warnings */
    ruleT__36Ex: ;

}
// $ANTLR end T__36

//   Comes from: 8:7: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__37
 *
 * Looks to match the characters the constitute the token T__37
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__37(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__37;


    // ./ExprCppTree.g:8:7: ( ')' )
    // ./ExprCppTree.g:8:9: ')'
    {
        MATCHC(')');
        if  (HASEXCEPTION())
        {
            goto ruleT__37Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__37Ex; /* Prevent compiler warnings */
    ruleT__37Ex: ;

}
// $ANTLR end T__37

//   Comes from: 9:7: ( ':' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__38
 *
 * Looks to match the characters the constitute the token T__38
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__38(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__38;


    // ./ExprCppTree.g:9:7: ( ':' )
    // ./ExprCppTree.g:9:9: ':'
    {
        MATCHC(':');
        if  (HASEXCEPTION())
        {
            goto ruleT__38Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__38Ex; /* Prevent compiler warnings */
    ruleT__38Ex: ;

}
// $ANTLR end T__38

//   Comes from: 10:7: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__39
 *
 * Looks to match the characters the constitute the token T__39
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__39(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__39;


    // ./ExprCppTree.g:10:7: ( ';' )
    // ./ExprCppTree.g:10:9: ';'
    {
        MATCHC(';');
        if  (HASEXCEPTION())
        {
            goto ruleT__39Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__39Ex; /* Prevent compiler warnings */
    ruleT__39Ex: ;

}
// $ANTLR end T__39

//   Comes from: 11:7: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__40
 *
 * Looks to match the characters the constitute the token T__40
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__40(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__40;


    // ./ExprCppTree.g:11:7: ( '{' )
    // ./ExprCppTree.g:11:9: '{'
    {
        MATCHC('{');
        if  (HASEXCEPTION())
        {
            goto ruleT__40Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__40Ex; /* Prevent compiler warnings */
    ruleT__40Ex: ;

}
// $ANTLR end T__40

//   Comes from: 12:7: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__41
 *
 * Looks to match the characters the constitute the token T__41
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__41(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__41;


    // ./ExprCppTree.g:12:7: ( '}' )
    // ./ExprCppTree.g:12:9: '}'
    {
        MATCHC('}');
        if  (HASEXCEPTION())
        {
            goto ruleT__41Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__41Ex; /* Prevent compiler warnings */
    ruleT__41Ex: ;

}
// $ANTLR end T__41

//   Comes from: 14:5: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PLUS
 *
 * Looks to match the characters the constitute the token PLUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPLUS(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PLUS;


    // ./ExprCppTree.g:14:5: ( '+' )
    // ./ExprCppTree.g:14:7: '+'
    {
        MATCHC('+');
        if  (HASEXCEPTION())
        {
            goto rulePLUSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto rulePLUSEx; /* Prevent compiler warnings */
    rulePLUSEx: ;

}
// $ANTLR end PLUS

//   Comes from: 15:6: ( '-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MINUS
 *
 * Looks to match the characters the constitute the token MINUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMINUS(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = MINUS;


    // ./ExprCppTree.g:15:6: ( '-' )
    // ./ExprCppTree.g:15:8: '-'
    {
        MATCHC('-');
        if  (HASEXCEPTION())
        {
            goto ruleMINUSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleMINUSEx; /* Prevent compiler warnings */
    ruleMINUSEx: ;

}
// $ANTLR end MINUS

//   Comes from: 16:6: ( '*' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start TIMES
 *
 * Looks to match the characters the constitute the token TIMES
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mTIMES(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = TIMES;


    // ./ExprCppTree.g:16:6: ( '*' )
    // ./ExprCppTree.g:16:8: '*'
    {
        MATCHC('*');
        if  (HASEXCEPTION())
        {
            goto ruleTIMESEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleTIMESEx; /* Prevent compiler warnings */
    ruleTIMESEx: ;

}
// $ANTLR end TIMES

//   Comes from: 17:4: ( '/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DIV
 *
 * Looks to match the characters the constitute the token DIV
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDIV(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DIV;


    // ./ExprCppTree.g:17:4: ( '/' )
    // ./ExprCppTree.g:17:6: '/'
    {
        MATCHC('/');
        if  (HASEXCEPTION())
        {
            goto ruleDIVEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleDIVEx; /* Prevent compiler warnings */
    ruleDIVEx: ;

}
// $ANTLR end DIV

//   Comes from: 18:4: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DOT
 *
 * Looks to match the characters the constitute the token DOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDOT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DOT;


    // ./ExprCppTree.g:18:4: ( ',' )
    // ./ExprCppTree.g:18:6: ','
    {
        MATCHC(',');
        if  (HASEXCEPTION())
        {
            goto ruleDOTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleDOTEx; /* Prevent compiler warnings */
    ruleDOTEx: ;

}
// $ANTLR end DOT

//   Comes from: 19:7: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ASSIGN
 *
 * Looks to match the characters the constitute the token ASSIGN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mASSIGN(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ASSIGN;


    // ./ExprCppTree.g:19:7: ( '=' )
    // ./ExprCppTree.g:19:9: '='
    {
        MATCHC('=');
        if  (HASEXCEPTION())
        {
            goto ruleASSIGNEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleASSIGNEx; /* Prevent compiler warnings */
    ruleASSIGNEx: ;

}
// $ANTLR end ASSIGN

//   Comes from: 21:4: ( 'def' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DEF
 *
 * Looks to match the characters the constitute the token DEF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDEF(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DEF;


    // ./ExprCppTree.g:21:4: ( 'def' )
    // ./ExprCppTree.g:21:6: 'def'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleDEFEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleDEFEx; /* Prevent compiler warnings */
    ruleDEFEx: ;

}
// $ANTLR end DEF

//   Comes from: 22:3: ( 'if' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start IF
 *
 * Looks to match the characters the constitute the token IF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mIF(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = IF;


    // ./ExprCppTree.g:22:3: ( 'if' )
    // ./ExprCppTree.g:22:5: 'if'
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleIFEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleIFEx; /* Prevent compiler warnings */
    ruleIFEx: ;

}
// $ANTLR end IF

//   Comes from: 23:5: ( 'else' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ELSE
 *
 * Looks to match the characters the constitute the token ELSE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mELSE(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ELSE;


    // ./ExprCppTree.g:23:5: ( 'else' )
    // ./ExprCppTree.g:23:7: 'else'
    {
        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleELSEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleELSEEx; /* Prevent compiler warnings */
    ruleELSEEx: ;

}
// $ANTLR end ELSE

//   Comes from: 25:3: ( '>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start GT
 *
 * Looks to match the characters the constitute the token GT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mGT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = GT;


    // ./ExprCppTree.g:25:3: ( '>' )
    // ./ExprCppTree.g:25:5: '>'
    {
        MATCHC('>');
        if  (HASEXCEPTION())
        {
            goto ruleGTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleGTEx; /* Prevent compiler warnings */
    ruleGTEx: ;

}
// $ANTLR end GT

//   Comes from: 26:4: ( '>=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start GEQ
 *
 * Looks to match the characters the constitute the token GEQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mGEQ(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = GEQ;


    // ./ExprCppTree.g:26:4: ( '>=' )
    // ./ExprCppTree.g:26:6: '>='
    {
        MATCHS(lit_4);
        if  (HASEXCEPTION())
        {
            goto ruleGEQEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleGEQEx; /* Prevent compiler warnings */
    ruleGEQEx: ;

}
// $ANTLR end GEQ

//   Comes from: 27:3: ( '<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LS
 *
 * Looks to match the characters the constitute the token LS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLS(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LS;


    // ./ExprCppTree.g:27:3: ( '<' )
    // ./ExprCppTree.g:27:5: '<'
    {
        MATCHC('<');
        if  (HASEXCEPTION())
        {
            goto ruleLSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLSEx; /* Prevent compiler warnings */
    ruleLSEx: ;

}
// $ANTLR end LS

//   Comes from: 28:4: ( '<=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LEQ
 *
 * Looks to match the characters the constitute the token LEQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLEQ(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LEQ;


    // ./ExprCppTree.g:28:4: ( '<=' )
    // ./ExprCppTree.g:28:6: '<='
    {
        MATCHS(lit_5);
        if  (HASEXCEPTION())
        {
            goto ruleLEQEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLEQEx; /* Prevent compiler warnings */
    ruleLEQEx: ;

}
// $ANTLR end LEQ

//   Comes from: 29:3: ( '==' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EQ
 *
 * Looks to match the characters the constitute the token EQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEQ(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = EQ;


    // ./ExprCppTree.g:29:3: ( '==' )
    // ./ExprCppTree.g:29:5: '=='
    {
        MATCHS(lit_6);
        if  (HASEXCEPTION())
        {
            goto ruleEQEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleEQEx; /* Prevent compiler warnings */
    ruleEQEx: ;

}
// $ANTLR end EQ

//   Comes from: 30:4: ( '!' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NOT
 *
 * Looks to match the characters the constitute the token NOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNOT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NOT;


    // ./ExprCppTree.g:30:4: ( '!' )
    // ./ExprCppTree.g:30:6: '!'
    {
        MATCHC('!');
        if  (HASEXCEPTION())
        {
            goto ruleNOTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNOTEx; /* Prevent compiler warnings */
    ruleNOTEx: ;

}
// $ANTLR end NOT

//   Comes from: 31:3: ( '||' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OR
 *
 * Looks to match the characters the constitute the token OR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOR(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OR;


    // ./ExprCppTree.g:31:3: ( '||' )
    // ./ExprCppTree.g:31:5: '||'
    {
        MATCHS(lit_7);
        if  (HASEXCEPTION())
        {
            goto ruleOREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOREx; /* Prevent compiler warnings */
    ruleOREx: ;

}
// $ANTLR end OR

//   Comes from: 32:4: ( '&&' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start AND
 *
 * Looks to match the characters the constitute the token AND
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mAND(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = AND;


    // ./ExprCppTree.g:32:4: ( '&&' )
    // ./ExprCppTree.g:32:6: '&&'
    {
        MATCHS(lit_8);
        if  (HASEXCEPTION())
        {
            goto ruleANDEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleANDEx; /* Prevent compiler warnings */
    ruleANDEx: ;

}
// $ANTLR end AND

//   Comes from: 33:6: ( '|' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BITOR
 *
 * Looks to match the characters the constitute the token BITOR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBITOR(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = BITOR;


    // ./ExprCppTree.g:33:6: ( '|' )
    // ./ExprCppTree.g:33:8: '|'
    {
        MATCHC('|');
        if  (HASEXCEPTION())
        {
            goto ruleBITOREx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleBITOREx; /* Prevent compiler warnings */
    ruleBITOREx: ;

}
// $ANTLR end BITOR

//   Comes from: 34:7: ( '&' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BITAND
 *
 * Looks to match the characters the constitute the token BITAND
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBITAND(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = BITAND;


    // ./ExprCppTree.g:34:7: ( '&' )
    // ./ExprCppTree.g:34:9: '&'
    {
        MATCHC('&');
        if  (HASEXCEPTION())
        {
            goto ruleBITANDEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleBITANDEx; /* Prevent compiler warnings */
    ruleBITANDEx: ;

}
// $ANTLR end BITAND

//   Comes from: 36:6: ( 'print' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PRINT
 *
 * Looks to match the characters the constitute the token PRINT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPRINT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PRINT;


    // ./ExprCppTree.g:36:6: ( 'print' )
    // ./ExprCppTree.g:36:8: 'print'
    {
        MATCHS(lit_9);
        if  (HASEXCEPTION())
        {
            goto rulePRINTEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto rulePRINTEx; /* Prevent compiler warnings */
    rulePRINTEx: ;

}
// $ANTLR end PRINT

//   Comes from: 37:4: ( 'for' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start FOR
 *
 * Looks to match the characters the constitute the token FOR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mFOR(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = FOR;


    // ./ExprCppTree.g:37:4: ( 'for' )
    // ./ExprCppTree.g:37:6: 'for'
    {
        MATCHS(lit_10);
        if  (HASEXCEPTION())
        {
            goto ruleFOREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleFOREx; /* Prevent compiler warnings */
    ruleFOREx: ;

}
// $ANTLR end FOR

//   Comes from: 38:6: ( 'while' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WHILE
 *
 * Looks to match the characters the constitute the token WHILE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWHILE(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WHILE;


    // ./ExprCppTree.g:38:6: ( 'while' )
    // ./ExprCppTree.g:38:8: 'while'
    {
        MATCHS(lit_11);
        if  (HASEXCEPTION())
        {
            goto ruleWHILEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWHILEEx; /* Prevent compiler warnings */
    ruleWHILEEx: ;

}
// $ANTLR end WHILE

//   Comes from: 39:7: ( 'switch' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start SWITCH
 *
 * Looks to match the characters the constitute the token SWITCH
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSWITCH(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = SWITCH;


    // ./ExprCppTree.g:39:7: ( 'switch' )
    // ./ExprCppTree.g:39:9: 'switch'
    {
        MATCHS(lit_12);
        if  (HASEXCEPTION())
        {
            goto ruleSWITCHEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSWITCHEx; /* Prevent compiler warnings */
    ruleSWITCHEx: ;

}
// $ANTLR end SWITCH

//   Comes from: 40:5: ( 'case' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CASE
 *
 * Looks to match the characters the constitute the token CASE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCASE(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CASE;


    // ./ExprCppTree.g:40:5: ( 'case' )
    // ./ExprCppTree.g:40:7: 'case'
    {
        MATCHS(lit_13);
        if  (HASEXCEPTION())
        {
            goto ruleCASEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCASEEx; /* Prevent compiler warnings */
    ruleCASEEx: ;

}
// $ANTLR end CASE

//   Comes from: 41:8: ( 'default' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DEFAULT
 *
 * Looks to match the characters the constitute the token DEFAULT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDEFAULT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DEFAULT;


    // ./ExprCppTree.g:41:8: ( 'default' )
    // ./ExprCppTree.g:41:10: 'default'
    {
        MATCHS(lit_14);
        if  (HASEXCEPTION())
        {
            goto ruleDEFAULTEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleDEFAULTEx; /* Prevent compiler warnings */
    ruleDEFAULTEx: ;

}
// $ANTLR end DEFAULT

//   Comes from: 42:6: ( 'break' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BREAK
 *
 * Looks to match the characters the constitute the token BREAK
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBREAK(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = BREAK;


    // ./ExprCppTree.g:42:6: ( 'break' )
    // ./ExprCppTree.g:42:8: 'break'
    {
        MATCHS(lit_15);
        if  (HASEXCEPTION())
        {
            goto ruleBREAKEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleBREAKEx; /* Prevent compiler warnings */
    ruleBREAKEx: ;

}
// $ANTLR end BREAK

//   Comes from: 43:9: ( 'continue' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CONTINUE
 *
 * Looks to match the characters the constitute the token CONTINUE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCONTINUE(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CONTINUE;


    // ./ExprCppTree.g:43:9: ( 'continue' )
    // ./ExprCppTree.g:43:11: 'continue'
    {
        MATCHS(lit_16);
        if  (HASEXCEPTION())
        {
            goto ruleCONTINUEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCONTINUEEx; /* Prevent compiler warnings */
    ruleCONTINUEEx: ;

}
// $ANTLR end CONTINUE

//   Comes from: 94:3: ( ( 'a' .. 'z' | 'A' .. 'Z' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ID
 *
 * Looks to match the characters the constitute the token ID
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mID(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ID;


    // ./ExprCppTree.g:94:3: ( ( 'a' .. 'z' | 'A' .. 'Z' )+ )
    // ./ExprCppTree.g:94:5: ( 'a' .. 'z' | 'A' .. 'Z' )+
    {
        // ./ExprCppTree.g:94:5: ( 'a' .. 'z' | 'A' .. 'Z' )+
        {
            int cnt1=0;

            for (;;)
            {
                int alt1=2;
        	switch ( LA(1) )
        	{
        	case 'A':
        	case 'B':
        	case 'C':
        	case 'D':
        	case 'E':
        	case 'F':
        	case 'G':
        	case 'H':
        	case 'I':
        	case 'J':
        	case 'K':
        	case 'L':
        	case 'M':
        	case 'N':
        	case 'O':
        	case 'P':
        	case 'Q':
        	case 'R':
        	case 'S':
        	case 'T':
        	case 'U':
        	case 'V':
        	case 'W':
        	case 'X':
        	case 'Y':
        	case 'Z':
        	case 'a':
        	case 'b':
        	case 'c':
        	case 'd':
        	case 'e':
        	case 'f':
        	case 'g':
        	case 'h':
        	case 'i':
        	case 'j':
        	case 'k':
        	case 'l':
        	case 'm':
        	case 'n':
        	case 'o':
        	case 'p':
        	case 'q':
        	case 'r':
        	case 's':
        	case 't':
        	case 'u':
        	case 'v':
        	case 'w':
        	case 'x':
        	case 'y':
        	case 'z':
        		{
        			alt1=1;
        		}
        	    break;

        	}

        	switch (alt1)
        	{
        	    case 1:
        	        // ./ExprCppTree.g:
        	        {
        	            if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleIDEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt1 >= 1 )
        		{
        		    goto loop1;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleIDEx;
        	}
        	cnt1++;
            }
            loop1: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleIDEx; /* Prevent compiler warnings */
    ruleIDEx: ;

}
// $ANTLR end ID

//   Comes from: 96:4: ( ( '-' )? ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INT
 *
 * Looks to match the characters the constitute the token INT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INT;


    // ./ExprCppTree.g:96:4: ( ( '-' )? ( '0' .. '9' )+ )
    // ./ExprCppTree.g:96:6: ( '-' )? ( '0' .. '9' )+
    {
        // ./ExprCppTree.g:96:6: ( '-' )?
        {
            int alt2=2;
            switch ( LA(1) )
            {
                case '-':
                	{
                		alt2=1;
                	}
                    break;
            }

            switch (alt2)
            {
        	case 1:
        	    // ./ExprCppTree.g:96:6: '-'
        	    {
        	        MATCHC('-');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleINTEx;
        	        }


        	    }
        	    break;

            }
        }

        // ./ExprCppTree.g:96:11: ( '0' .. '9' )+
        {
            int cnt3=0;

            for (;;)
            {
                int alt3=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt3=1;
        		}
        	    break;

        	}

        	switch (alt3)
        	{
        	    case 1:
        	        // ./ExprCppTree.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleINTEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt3 >= 1 )
        		{
        		    goto loop3;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleINTEx;
        	}
        	cnt3++;
            }
            loop3: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleINTEx; /* Prevent compiler warnings */
    ruleINTEx: ;

}
// $ANTLR end INT

//   Comes from: 97:7: ( '\\'' ( . )* '\\'' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING
 *
 * Looks to match the characters the constitute the token STRING
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = STRING;


    // ./ExprCppTree.g:97:7: ( '\\'' ( . )* '\\'' )
    // ./ExprCppTree.g:97:9: '\\'' ( . )* '\\''
    {
        MATCHC('\'');
        if  (HASEXCEPTION())
        {
            goto ruleSTRINGEx;
        }


        // ./ExprCppTree.g:97:14: ( . )*

        for (;;)
        {
            int alt4=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA4_0 = LA(1);
                if ( (LA4_0 == '\''))
                {
                    alt4=2;
                }
                else if ( (((LA4_0 >= 0x0000) && (LA4_0 <= '&')) || ((LA4_0 >= '(') && (LA4_0 <= 0xFFFF))))
                {
                    alt4=1;
                }

            }
            switch (alt4)
            {
        	case 1:
        	    // ./ExprCppTree.g:97:14: .
        	    {
        	        MATCHANY();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleSTRINGEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop4;	/* break out of the loop */
        	    break;
            }
        }
        loop4: ; /* Jump out to here if this rule does not match */


        MATCHC('\'');
        if  (HASEXCEPTION())
        {
            goto ruleSTRINGEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSTRINGEx; /* Prevent compiler warnings */
    ruleSTRINGEx: ;

}
// $ANTLR end STRING

//   Comes from: 98:6: ( '{}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BLOCK
 *
 * Looks to match the characters the constitute the token BLOCK
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBLOCK(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = BLOCK;


    // ./ExprCppTree.g:98:6: ( '{}' )
    // ./ExprCppTree.g:98:7: '{}'
    {
        MATCHS(lit_17);
        if  (HASEXCEPTION())
        {
            goto ruleBLOCKEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleBLOCKEx; /* Prevent compiler warnings */
    ruleBLOCKEx: ;

}
// $ANTLR end BLOCK

//   Comes from: 99:4: ( ( ' ' | '\\t' | '\\n' | '\\r' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;


    // ./ExprCppTree.g:99:4: ( ( ' ' | '\\t' | '\\n' | '\\r' )+ )
    // ./ExprCppTree.g:99:6: ( ' ' | '\\t' | '\\n' | '\\r' )+
    {
        // ./ExprCppTree.g:99:6: ( ' ' | '\\t' | '\\n' | '\\r' )+
        {
            int cnt5=0;

            for (;;)
            {
                int alt5=2;
        	switch ( LA(1) )
        	{
        	case '\t':
        	case '\n':
        	case '\r':
        	case ' ':
        		{
        			alt5=1;
        		}
        	    break;

        	}

        	switch (alt5)
        	{
        	    case 1:
        	        // ./ExprCppTree.g:
        	        {
        	            if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleWSEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt5 >= 1 )
        		{
        		    goto loop5;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWSEx;
        	}
        	cnt5++;
            }
            loop5: ;	/* Jump to here if this rule does not match */
        }

        {
            LEXSTATE->channel = HIDDEN;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pExprCppTreeLexer ctx)
{
    {
        //  ./ExprCppTree.g:1:8: ( T__36 | T__37 | T__38 | T__39 | T__40 | T__41 | PLUS | MINUS | TIMES | DIV | DOT | ASSIGN | DEF | IF | ELSE | GT | GEQ | LS | LEQ | EQ | NOT | OR | AND | BITOR | BITAND | PRINT | FOR | WHILE | SWITCH | CASE | DEFAULT | BREAK | CONTINUE | ID | INT | STRING | BLOCK | WS )

        ANTLR3_UINT32 alt6;

        alt6=38;

        switch ( LA(1) )
        {
        case '(':
        	{
        		alt6=1;
        	}
            break;
        case ')':
        	{
        		alt6=2;
        	}
            break;
        case ':':
        	{
        		alt6=3;
        	}
            break;
        case ';':
        	{
        		alt6=4;
        	}
            break;
        case '{':
        	{
        		switch ( LA(2) )
        		{
        		case '}':
        			{
        				alt6=37;
        			}
        		    break;

        		default:
        		    alt6=5;
        		}

        	}
            break;
        case '}':
        	{
        		alt6=6;
        	}
            break;
        case '+':
        	{
        		alt6=7;
        	}
            break;
        case '-':
        	{
        		switch ( LA(2) )
        		{
        		case '0':
        		case '1':
        		case '2':
        		case '3':
        		case '4':
        		case '5':
        		case '6':
        		case '7':
        		case '8':
        		case '9':
        			{
        				alt6=35;
        			}
        		    break;

        		default:
        		    alt6=8;
        		}

        	}
            break;
        case '*':
        	{
        		alt6=9;
        	}
            break;
        case '/':
        	{
        		alt6=10;
        	}
            break;
        case ',':
        	{
        		alt6=11;
        	}
            break;
        case '=':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt6=20;
        			}
        		    break;

        		default:
        		    alt6=12;
        		}

        	}
            break;
        case 'd':
        	{
        		switch ( LA(2) )
        		{
        		case 'e':
        			{
        				switch ( LA(3) )
        				{
        				case 'f':
        					{
        						switch ( LA(4) )
        						{
        						case 'a':
        							{
        								switch ( LA(5) )
        								{
        								case 'u':
        									{
        										switch ( LA(6) )
        										{
        										case 'l':
        											{
        												switch ( LA(7) )
        												{
        												case 't':
        													{
        														switch ( LA(8) )
        														{
        														case 'A':
        														case 'B':
        														case 'C':
        														case 'D':
        														case 'E':
        														case 'F':
        														case 'G':
        														case 'H':
        														case 'I':
        														case 'J':
        														case 'K':
        														case 'L':
        														case 'M':
        														case 'N':
        														case 'O':
        														case 'P':
        														case 'Q':
        														case 'R':
        														case 'S':
        														case 'T':
        														case 'U':
        														case 'V':
        														case 'W':
        														case 'X':
        														case 'Y':
        														case 'Z':
        														case 'a':
        														case 'b':
        														case 'c':
        														case 'd':
        														case 'e':
        														case 'f':
        														case 'g':
        														case 'h':
        														case 'i':
        														case 'j':
        														case 'k':
        														case 'l':
        														case 'm':
        														case 'n':
        														case 'o':
        														case 'p':
        														case 'q':
        														case 'r':
        														case 's':
        														case 't':
        														case 'u':
        														case 'v':
        														case 'w':
        														case 'x':
        														case 'y':
        														case 'z':
        															{
        																alt6=34;
        															}
        														    break;

        														default:
        														    alt6=31;
        														}

        													}
        												    break;

        												default:
        												    alt6=34;
        												}

        											}
        										    break;

        										default:
        										    alt6=34;
        										}

        									}
        								    break;

        								default:
        								    alt6=34;
        								}

        							}
        						    break;
        						case 'A':
        						case 'B':
        						case 'C':
        						case 'D':
        						case 'E':
        						case 'F':
        						case 'G':
        						case 'H':
        						case 'I':
        						case 'J':
        						case 'K':
        						case 'L':
        						case 'M':
        						case 'N':
        						case 'O':
        						case 'P':
        						case 'Q':
        						case 'R':
        						case 'S':
        						case 'T':
        						case 'U':
        						case 'V':
        						case 'W':
        						case 'X':
        						case 'Y':
        						case 'Z':
        						case 'b':
        						case 'c':
        						case 'd':
        						case 'e':
        						case 'f':
        						case 'g':
        						case 'h':
        						case 'i':
        						case 'j':
        						case 'k':
        						case 'l':
        						case 'm':
        						case 'n':
        						case 'o':
        						case 'p':
        						case 'q':
        						case 'r':
        						case 's':
        						case 't':
        						case 'u':
        						case 'v':
        						case 'w':
        						case 'x':
        						case 'y':
        						case 'z':
        							{
        								alt6=34;
        							}
        						    break;

        						default:
        						    alt6=13;
        						}

        					}
        				    break;

        				default:
        				    alt6=34;
        				}

        			}
        		    break;

        		default:
        		    alt6=34;
        		}

        	}
            break;
        case 'i':
        	{
        		switch ( LA(2) )
        		{
        		case 'f':
        			{
        				switch ( LA(3) )
        				{
        				case 'A':
        				case 'B':
        				case 'C':
        				case 'D':
        				case 'E':
        				case 'F':
        				case 'G':
        				case 'H':
        				case 'I':
        				case 'J':
        				case 'K':
        				case 'L':
        				case 'M':
        				case 'N':
        				case 'O':
        				case 'P':
        				case 'Q':
        				case 'R':
        				case 'S':
        				case 'T':
        				case 'U':
        				case 'V':
        				case 'W':
        				case 'X':
        				case 'Y':
        				case 'Z':
        				case 'a':
        				case 'b':
        				case 'c':
        				case 'd':
        				case 'e':
        				case 'f':
        				case 'g':
        				case 'h':
        				case 'i':
        				case 'j':
        				case 'k':
        				case 'l':
        				case 'm':
        				case 'n':
        				case 'o':
        				case 'p':
        				case 'q':
        				case 'r':
        				case 's':
        				case 't':
        				case 'u':
        				case 'v':
        				case 'w':
        				case 'x':
        				case 'y':
        				case 'z':
        					{
        						alt6=34;
        					}
        				    break;

        				default:
        				    alt6=14;
        				}

        			}
        		    break;

        		default:
        		    alt6=34;
        		}

        	}
            break;
        case 'e':
        	{
        		switch ( LA(2) )
        		{
        		case 'l':
        			{
        				switch ( LA(3) )
        				{
        				case 's':
        					{
        						switch ( LA(4) )
        						{
        						case 'e':
        							{
        								switch ( LA(5) )
        								{
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt6=34;
        									}
        								    break;

        								default:
        								    alt6=15;
        								}

        							}
        						    break;

        						default:
        						    alt6=34;
        						}

        					}
        				    break;

        				default:
        				    alt6=34;
        				}

        			}
        		    break;

        		default:
        		    alt6=34;
        		}

        	}
            break;
        case '>':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt6=17;
        			}
        		    break;

        		default:
        		    alt6=16;
        		}

        	}
            break;
        case '<':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt6=19;
        			}
        		    break;

        		default:
        		    alt6=18;
        		}

        	}
            break;
        case '!':
        	{
        		alt6=21;
        	}
            break;
        case '|':
        	{
        		switch ( LA(2) )
        		{
        		case '|':
        			{
        				alt6=22;
        			}
        		    break;

        		default:
        		    alt6=24;
        		}

        	}
            break;
        case '&':
        	{
        		switch ( LA(2) )
        		{
        		case '&':
        			{
        				alt6=23;
        			}
        		    break;

        		default:
        		    alt6=25;
        		}

        	}
            break;
        case 'p':
        	{
        		switch ( LA(2) )
        		{
        		case 'r':
        			{
        				switch ( LA(3) )
        				{
        				case 'i':
        					{
        						switch ( LA(4) )
        						{
        						case 'n':
        							{
        								switch ( LA(5) )
        								{
        								case 't':
        									{
        										switch ( LA(6) )
        										{
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt6=34;
        											}
        										    break;

        										default:
        										    alt6=26;
        										}

        									}
        								    break;

        								default:
        								    alt6=34;
        								}

        							}
        						    break;

        						default:
        						    alt6=34;
        						}

        					}
        				    break;

        				default:
        				    alt6=34;
        				}

        			}
        		    break;

        		default:
        		    alt6=34;
        		}

        	}
            break;
        case 'f':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'r':
        					{
        						switch ( LA(4) )
        						{
        						case 'A':
        						case 'B':
        						case 'C':
        						case 'D':
        						case 'E':
        						case 'F':
        						case 'G':
        						case 'H':
        						case 'I':
        						case 'J':
        						case 'K':
        						case 'L':
        						case 'M':
        						case 'N':
        						case 'O':
        						case 'P':
        						case 'Q':
        						case 'R':
        						case 'S':
        						case 'T':
        						case 'U':
        						case 'V':
        						case 'W':
        						case 'X':
        						case 'Y':
        						case 'Z':
        						case 'a':
        						case 'b':
        						case 'c':
        						case 'd':
        						case 'e':
        						case 'f':
        						case 'g':
        						case 'h':
        						case 'i':
        						case 'j':
        						case 'k':
        						case 'l':
        						case 'm':
        						case 'n':
        						case 'o':
        						case 'p':
        						case 'q':
        						case 'r':
        						case 's':
        						case 't':
        						case 'u':
        						case 'v':
        						case 'w':
        						case 'x':
        						case 'y':
        						case 'z':
        							{
        								alt6=34;
        							}
        						    break;

        						default:
        						    alt6=27;
        						}

        					}
        				    break;

        				default:
        				    alt6=34;
        				}

        			}
        		    break;

        		default:
        		    alt6=34;
        		}

        	}
            break;
        case 'w':
        	{
        		switch ( LA(2) )
        		{
        		case 'h':
        			{
        				switch ( LA(3) )
        				{
        				case 'i':
        					{
        						switch ( LA(4) )
        						{
        						case 'l':
        							{
        								switch ( LA(5) )
        								{
        								case 'e':
        									{
        										switch ( LA(6) )
        										{
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt6=34;
        											}
        										    break;

        										default:
        										    alt6=28;
        										}

        									}
        								    break;

        								default:
        								    alt6=34;
        								}

        							}
        						    break;

        						default:
        						    alt6=34;
        						}

        					}
        				    break;

        				default:
        				    alt6=34;
        				}

        			}
        		    break;

        		default:
        		    alt6=34;
        		}

        	}
            break;
        case 's':
        	{
        		switch ( LA(2) )
        		{
        		case 'w':
        			{
        				switch ( LA(3) )
        				{
        				case 'i':
        					{
        						switch ( LA(4) )
        						{
        						case 't':
        							{
        								switch ( LA(5) )
        								{
        								case 'c':
        									{
        										switch ( LA(6) )
        										{
        										case 'h':
        											{
        												switch ( LA(7) )
        												{
        												case 'A':
        												case 'B':
        												case 'C':
        												case 'D':
        												case 'E':
        												case 'F':
        												case 'G':
        												case 'H':
        												case 'I':
        												case 'J':
        												case 'K':
        												case 'L':
        												case 'M':
        												case 'N':
        												case 'O':
        												case 'P':
        												case 'Q':
        												case 'R':
        												case 'S':
        												case 'T':
        												case 'U':
        												case 'V':
        												case 'W':
        												case 'X':
        												case 'Y':
        												case 'Z':
        												case 'a':
        												case 'b':
        												case 'c':
        												case 'd':
        												case 'e':
        												case 'f':
        												case 'g':
        												case 'h':
        												case 'i':
        												case 'j':
        												case 'k':
        												case 'l':
        												case 'm':
        												case 'n':
        												case 'o':
        												case 'p':
        												case 'q':
        												case 'r':
        												case 's':
        												case 't':
        												case 'u':
        												case 'v':
        												case 'w':
        												case 'x':
        												case 'y':
        												case 'z':
        													{
        														alt6=34;
        													}
        												    break;

        												default:
        												    alt6=29;
        												}

        											}
        										    break;

        										default:
        										    alt6=34;
        										}

        									}
        								    break;

        								default:
        								    alt6=34;
        								}

        							}
        						    break;

        						default:
        						    alt6=34;
        						}

        					}
        				    break;

        				default:
        				    alt6=34;
        				}

        			}
        		    break;

        		default:
        		    alt6=34;
        		}

        	}
            break;
        case 'c':
        	{
        		switch ( LA(2) )
        		{
        		case 'a':
        			{
        				switch ( LA(3) )
        				{
        				case 's':
        					{
        						switch ( LA(4) )
        						{
        						case 'e':
        							{
        								switch ( LA(5) )
        								{
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt6=34;
        									}
        								    break;

        								default:
        								    alt6=30;
        								}

        							}
        						    break;

        						default:
        						    alt6=34;
        						}

        					}
        				    break;

        				default:
        				    alt6=34;
        				}

        			}
        		    break;
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'n':
        					{
        						switch ( LA(4) )
        						{
        						case 't':
        							{
        								switch ( LA(5) )
        								{
        								case 'i':
        									{
        										switch ( LA(6) )
        										{
        										case 'n':
        											{
        												switch ( LA(7) )
        												{
        												case 'u':
        													{
        														switch ( LA(8) )
        														{
        														case 'e':
        															{
        																switch ( LA(9) )
        																{
        																case 'A':
        																case 'B':
        																case 'C':
        																case 'D':
        																case 'E':
        																case 'F':
        																case 'G':
        																case 'H':
        																case 'I':
        																case 'J':
        																case 'K':
        																case 'L':
        																case 'M':
        																case 'N':
        																case 'O':
        																case 'P':
        																case 'Q':
        																case 'R':
        																case 'S':
        																case 'T':
        																case 'U':
        																case 'V':
        																case 'W':
        																case 'X':
        																case 'Y':
        																case 'Z':
        																case 'a':
        																case 'b':
        																case 'c':
        																case 'd':
        																case 'e':
        																case 'f':
        																case 'g':
        																case 'h':
        																case 'i':
        																case 'j':
        																case 'k':
        																case 'l':
        																case 'm':
        																case 'n':
        																case 'o':
        																case 'p':
        																case 'q':
        																case 'r':
        																case 's':
        																case 't':
        																case 'u':
        																case 'v':
        																case 'w':
        																case 'x':
        																case 'y':
        																case 'z':
        																	{
        																		alt6=34;
        																	}
        																    break;

        																default:
        																    alt6=33;
        																}

        															}
        														    break;

        														default:
        														    alt6=34;
        														}

        													}
        												    break;

        												default:
        												    alt6=34;
        												}

        											}
        										    break;

        										default:
        										    alt6=34;
        										}

        									}
        								    break;

        								default:
        								    alt6=34;
        								}

        							}
        						    break;

        						default:
        						    alt6=34;
        						}

        					}
        				    break;

        				default:
        				    alt6=34;
        				}

        			}
        		    break;

        		default:
        		    alt6=34;
        		}

        	}
            break;
        case 'b':
        	{
        		switch ( LA(2) )
        		{
        		case 'r':
        			{
        				switch ( LA(3) )
        				{
        				case 'e':
        					{
        						switch ( LA(4) )
        						{
        						case 'a':
        							{
        								switch ( LA(5) )
        								{
        								case 'k':
        									{
        										switch ( LA(6) )
        										{
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt6=34;
        											}
        										    break;

        										default:
        										    alt6=32;
        										}

        									}
        								    break;

        								default:
        								    alt6=34;
        								}

        							}
        						    break;

        						default:
        						    alt6=34;
        						}

        					}
        				    break;

        				default:
        				    alt6=34;
        				}

        			}
        		    break;

        		default:
        		    alt6=34;
        		}

        	}
            break;
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case 'a':
        case 'g':
        case 'h':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'q':
        case 'r':
        case 't':
        case 'u':
        case 'v':
        case 'x':
        case 'y':
        case 'z':
        	{
        		alt6=34;
        	}
            break;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		alt6=35;
        	}
            break;
        case '\'':
        	{
        		alt6=36;
        	}
            break;
        case '\t':
        case '\n':
        case '\r':
        case ' ':
        	{
        		alt6=38;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 6;
            EXCEPTION->state        = 0;


            goto ruleTokensEx;

        }

        switch (alt6)
        {
    	case 1:
    	    // ./ExprCppTree.g:1:10: T__36
    	    {
    	        /* 1:10: T__36 */
    	        mT__36(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // ./ExprCppTree.g:1:16: T__37
    	    {
    	        /* 1:16: T__37 */
    	        mT__37(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // ./ExprCppTree.g:1:22: T__38
    	    {
    	        /* 1:22: T__38 */
    	        mT__38(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // ./ExprCppTree.g:1:28: T__39
    	    {
    	        /* 1:28: T__39 */
    	        mT__39(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // ./ExprCppTree.g:1:34: T__40
    	    {
    	        /* 1:34: T__40 */
    	        mT__40(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // ./ExprCppTree.g:1:40: T__41
    	    {
    	        /* 1:40: T__41 */
    	        mT__41(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // ./ExprCppTree.g:1:46: PLUS
    	    {
    	        /* 1:46: PLUS */
    	        mPLUS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // ./ExprCppTree.g:1:51: MINUS
    	    {
    	        /* 1:51: MINUS */
    	        mMINUS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // ./ExprCppTree.g:1:57: TIMES
    	    {
    	        /* 1:57: TIMES */
    	        mTIMES(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // ./ExprCppTree.g:1:63: DIV
    	    {
    	        /* 1:63: DIV */
    	        mDIV(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // ./ExprCppTree.g:1:67: DOT
    	    {
    	        /* 1:67: DOT */
    	        mDOT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // ./ExprCppTree.g:1:71: ASSIGN
    	    {
    	        /* 1:71: ASSIGN */
    	        mASSIGN(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // ./ExprCppTree.g:1:78: DEF
    	    {
    	        /* 1:78: DEF */
    	        mDEF(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // ./ExprCppTree.g:1:82: IF
    	    {
    	        /* 1:82: IF */
    	        mIF(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // ./ExprCppTree.g:1:85: ELSE
    	    {
    	        /* 1:85: ELSE */
    	        mELSE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // ./ExprCppTree.g:1:90: GT
    	    {
    	        /* 1:90: GT */
    	        mGT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // ./ExprCppTree.g:1:93: GEQ
    	    {
    	        /* 1:93: GEQ */
    	        mGEQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // ./ExprCppTree.g:1:97: LS
    	    {
    	        /* 1:97: LS */
    	        mLS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // ./ExprCppTree.g:1:100: LEQ
    	    {
    	        /* 1:100: LEQ */
    	        mLEQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // ./ExprCppTree.g:1:104: EQ
    	    {
    	        /* 1:104: EQ */
    	        mEQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // ./ExprCppTree.g:1:107: NOT
    	    {
    	        /* 1:107: NOT */
    	        mNOT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // ./ExprCppTree.g:1:111: OR
    	    {
    	        /* 1:111: OR */
    	        mOR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 23:
    	    // ./ExprCppTree.g:1:114: AND
    	    {
    	        /* 1:114: AND */
    	        mAND(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 24:
    	    // ./ExprCppTree.g:1:118: BITOR
    	    {
    	        /* 1:118: BITOR */
    	        mBITOR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 25:
    	    // ./ExprCppTree.g:1:124: BITAND
    	    {
    	        /* 1:124: BITAND */
    	        mBITAND(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 26:
    	    // ./ExprCppTree.g:1:131: PRINT
    	    {
    	        /* 1:131: PRINT */
    	        mPRINT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 27:
    	    // ./ExprCppTree.g:1:137: FOR
    	    {
    	        /* 1:137: FOR */
    	        mFOR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 28:
    	    // ./ExprCppTree.g:1:141: WHILE
    	    {
    	        /* 1:141: WHILE */
    	        mWHILE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 29:
    	    // ./ExprCppTree.g:1:147: SWITCH
    	    {
    	        /* 1:147: SWITCH */
    	        mSWITCH(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 30:
    	    // ./ExprCppTree.g:1:154: CASE
    	    {
    	        /* 1:154: CASE */
    	        mCASE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 31:
    	    // ./ExprCppTree.g:1:159: DEFAULT
    	    {
    	        /* 1:159: DEFAULT */
    	        mDEFAULT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 32:
    	    // ./ExprCppTree.g:1:167: BREAK
    	    {
    	        /* 1:167: BREAK */
    	        mBREAK(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 33:
    	    // ./ExprCppTree.g:1:173: CONTINUE
    	    {
    	        /* 1:173: CONTINUE */
    	        mCONTINUE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 34:
    	    // ./ExprCppTree.g:1:182: ID
    	    {
    	        /* 1:182: ID */
    	        mID(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 35:
    	    // ./ExprCppTree.g:1:185: INT
    	    {
    	        /* 1:185: INT */
    	        mINT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 36:
    	    // ./ExprCppTree.g:1:189: STRING
    	    {
    	        /* 1:189: STRING */
    	        mSTRING(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 37:
    	    // ./ExprCppTree.g:1:196: BLOCK
    	    {
    	        /* 1:196: BLOCK */
    	        mBLOCK(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 38:
    	    // ./ExprCppTree.g:1:202: WS
    	    {
    	        /* 1:202: WS */
    	        mWS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
